### ISSUE TITLE
XDZIBEC - Arbitrary Token Swap Vulnerability in DepositStableCoinToDealer Contract #L23

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#144]
XDZIBEC

medium

# Arbitrary Token Swap Vulnerability in DepositStableCoinToDealer Contract #L23

## Summary

in the `depositStableCoin` function, there is an external call using `swapTarget`. `call(data)'. The vulnerability i appears to be that the `swapTarget` contract can execute arbitrary code when the `depositStableCoin()` function is called. If an attacker is able to pass in a malicious `swapTarget` contract, they can execute any code they want, including stealing funds or causing other harm to the system. Additionally, the `approve`() function is being called twice for the asset token which can cause an unnecessary gas cost.

## Vulnerability Detail
 
the vulnerability lies in the `DepositStableCoinToDealer` contract's `depositStableCoin` function. 
Here is the line :

  ```solidity
function depositStableCoin(
        address asset,
        uint256 amount,
        address to,
        bytes calldata param,
        uint256 minReceive
    ) external {
        IERC20(asset).safeTransferFrom(msg.sender, address(this), amount);
        (address approveTarget, address swapTarget, bytes memory data) = abi
        .decode(param, (address, address, bytes));
```

Specifically, the function appears to accept an arbitrary contract address, `approval` target address, `swap` target address, and `swap` data as input via the `param` argument.

This could potentially allow an attacker to provide a malicious contract address, which could then execute arbitrary code when `swapTarget.call(data)` is called. Furthermore, if the attacker can control the `approveTarget` address or the data `parameter`, they may be able to `approve` arbitrary amounts of the asset token and perform other malicious actions, such as stealing user funds or minting new tokens.

It is worth noting that the `depositStableCoin` function does attempt to revert the transaction in case the `swapTarget.call(data)` call fails, but this does not prevent the attacker from potentially causing other damage before the revert is executed.

To address this vulnerability, it may be necessary to limit the `param` argument to a predefined set of contract addresses or ensure that any `arbitrary` addresses provided have been thoroughly `audited` and `approved`. Additionally, it may be necessary to add additional checks and safe guards to prevent malicious actions, such as checking the `approveTarget` address and data `parameter` for potential malicious behavior

## Impact
-The vulnerability allows an attacker to perform a reentrancy attack 
## Code Snippet

https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/stableCoin/DepositStableCoinToDealer.sol#L23

## Tool used

Manual Review

## Recommendation

in the `depositStableCoin` function, there is an external call using `swapTarget`. call( data)'. This can potentially lead to unexpected behavior if the called contract is malicious or contains a bug. To mitigate this, you can use the `OpenZeppelini` Address library and the 'functionCall' method to perform the external call with a custom error message.

Duplicate of #428

**Comment by sko94** [comment]
@sherlock-admin THANK YOU
