### ISSUE TITLE
rvierdiiev - User doesn't have ability to invalidate order with specific nonce

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#152]
rvierdiiev

high

# User doesn't have ability to invalidate order with specific nonce

## Summary
Currently user that signed order doesn't have ability to invalidate it, as nonce is not checked.
## Vulnerability Detail
User sign their orders offchain and provide nonce inside the message.
When message is hashed, then unique hash is computed, that can identify that order. If nonce is changed, then hash is changed as well.
Using this hash, `JOJOExternal.approveTrade` function is checking that [order can't be used to buy/sell more paper than was provided in the order](https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/impl/JOJOExternal.sol#L159-L163). So for example if order was signed to buy 5 papers, then trade executor can do trade as many times as he wishes with same order, but he can't buy more than 5 papersin total as it is provided in the order.

The problem here is next. User currently doesn't have control on his order, once he signed it. For example after signing order to buy 5 papers, user can change his mind and want to cancel this order. But he doesn't have such possibility. Another example is that his order is executed partially and 3 paper are already bought and now prices has changed, so user doesn't want to buy additional 2 papers. But executor still can trade this order. The only thing that can stop him [is expiration of the order](https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/impl/JOJOExternal.sol#L144-L147).
## Impact
User can't cancel his order.
## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/impl/JOJOExternal.sol#L132-L135
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/impl/JOJOExternal.sol#L158-L163
## Tool used

Manual Review

## Recommendation
Validate nonce inside order, allow user to invalidate specific nonce.

**Comment by rvierdiiev** [comment]
Escalate for 10 usdc. This is not same as #414.

414 is talking about possibility to replay order, which is not true. and this report is talking that order owner doesn't have ability to cancel it. pls, recheck this again.

**Comment by sherlock-admin** [comment]
> Escalate for 10 usdc. This is not same as #414.
> 
> 414 is talking about possibility to replay order, which is not true. and this report is talking that order owner doesn't have ability to cancel it. pls, recheck this again.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
In actual use, very few people will cancel the order on the chain, but they all use the free off-chain cancel, that is, they believe that the relayer will delete their order from the database.
If you don't trust the relayer, a better solution is to shorten the expired time signature.

**Comment by Trumpero** [comment]
The use of a nonce ensures that each order has a unique hash, even in cases where other fields of the orders are the same. If users are unable to cancel their orders on-chain, they should choose a fit expiration time. Therefore, I believe this issue should be a low/info since it doesn't cause any loss.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Although not a duplicate of #414, Based on the above comments considering this issue as low.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [rvierdiyev](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/152/#issuecomment-1568423673): accepted
