### ISSUE TITLE
RaymondFam - A malicious actor could make JUSDBank.deposit() run into DoS to other depositors when reserve.maxTotalDepositAmount is nearing to its cap

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#243]
RaymondFam

medium

# A malicious actor could make JUSDBank.deposit() run into DoS to other depositors when reserve.maxTotalDepositAmount is nearing to its cap

## Summary
In [JUSDV1](https://github.com/sherlock-audit/2023-04-jojo-raymondfam/tree/main/JUSDV1), `JUSDBank.deposit()` could be denied if a malicious actor is always there to front run the transaction with minute amount of collateral  just enough to make `reserve.totalDepositAmount > reserve.maxTotalDepositAmount` when `reserve.maxTotalDepositAmount` is `reserve.maxDepositAmountPerAccount` away from its capped limit.

## Vulnerability Detail
In `_deposit()`, the conditions for `reserve.maxDepositAmountPerAccount` and `reserve.maxTotalDepositAmount` are checked after the deposit has been made. If Bob, a malicious actor, can successfully front-run Alice's transaction that is intended to use up the last available quota, he can deposit 1 wei before her transaction is processed, causing her transaction to fail due to exceeding the maximum allowed deposit amounts.

## Impact
If Bob continues to do this every time Alice tries to deposit with a 1 wei reduced amount, Alice's deposits will repeatedly fail. This is a form of a front-running attack, which can be a potential vulnerability in the code.

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBank.sol#L93-L103
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBank.sol#L247-L271
## Tool used

Manual Review

## Recommendation
Consider having `_deposit()` refactored as follows:

```diff
    function _deposit(
        DataTypes.ReserveInfo storage reserve,
        DataTypes.UserInfo storage user,
        uint256 amount,
        address collateral,
        address to,
        address from
    ) internal {
        require(reserve.isDepositAllowed, JUSDErrors.RESERVE_NOT_ALLOW_DEPOSIT);
        require(amount != 0, JUSDErrors.DEPOSIT_AMOUNT_IS_ZERO);

+        _addCollateralIfNotExists(user, collateral);

+        uint256 availablePerAccount = reserve.maxDepositAmountPerAccount - user.depositBalance[collateral];
+        uint256 availableTotal = reserve.maxTotalDepositAmount - reserve.totalDepositAmount;

+        uint256 availableAmount = availablePerAccount < availableTotal ? availablePerAccount : availableTotal;
+        amount = amount > availableAmount ? availableAmount : amount;

        IERC20(collateral).safeTransferFrom(from, address(this), amount);
-        _addCollateralIfNotExists(user, collateral);
        user.depositBalance[collateral] += amount;
        reserve.totalDepositAmount += amount;
        require(
            user.depositBalance[collateral] <=
                reserve.maxDepositAmountPerAccount,
            JUSDErrors.EXCEED_THE_MAX_DEPOSIT_AMOUNT_PER_ACCOUNT
        );
        require(
            reserve.totalDepositAmount <= reserve.maxTotalDepositAmount,
            JUSDErrors.EXCEED_THE_MAX_DEPOSIT_AMOUNT_TOTAL
        );
        emit Deposit(collateral, from, to, msg.sender, amount);
    }
```
In this version, I calculate the available amounts for both per account and total deposit, and pick the lower of the two amounts as the `availableAmount`. Then, the function adjusts the `amount` to be the minimum of the original amount and the `availableAmount`. This way, the function will pick the lower of the two amounts, ensuring that neither of the caps is exceeded. The last two require checks may be removed where deemed fit.

**Comment by raymondfam** [comment]
Escalate for 10 USDC

This is a practical problem particularly when Bob in the scenario described is curently short of the needed collateral amount to use up the last quota left but yet going to be funded shortly with the needed collateral amount. Bob can drag on by repeatedly using the DOS attack given the lack of a minimum deposit amount where this type of attack could be sustained over an extended period.

It is important to address this issue as it may hamper the liquidity and overall usability of the protocol, creating unnecessary friction for users trying to deposit their assets.

The recommendation proposed in the submission would help mitigate this potential issue by ensuring the deposit doesn't exceed either of the caps (per account or total) before the deposit operation is performed. This change would not only protect against the described front-running attack, but would also help ensure fair access to deposit operations for all users.

This comment emphasizes the potential impact of the vulnerability and the feasibility of the attack, while also highlighting the value of the proposed solution. It also underlines the importance of proactive security measures rather than relying on 'impossibility' claims.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This is a practical problem particularly when Bob in the scenario described is curently short of the needed collateral amount to use up the last quota left but yet going to be funded shortly with the needed collateral amount. Bob can drag on by repeatedly using the DOS attack given the lack of a minimum deposit amount where this type of attack could be sustained over an extended period.
> 
> It is important to address this issue as it may hamper the liquidity and overall usability of the protocol, creating unnecessary friction for users trying to deposit their assets.
> 
> The recommendation proposed in the submission would help mitigate this potential issue by ensuring the deposit doesn't exceed either of the caps (per account or total) before the deposit operation is performed. This change would not only protect against the described front-running attack, but would also help ensure fair access to deposit operations for all users.
> 
> This comment emphasizes the potential impact of the vulnerability and the feasibility of the attack, while also highlighting the value of the proposed solution. It also underlines the importance of proactive security measures rather than relying on 'impossibility' claims.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
It is possible that this problem exists, but it happens too infrequently and it is not profitable. The existence of the situation must be in the place where MEV is relatively serious, such as the Eth, so we think it is possible to give a low issue.

**Comment by Trumpero** [comment]
The impact of this issue is low because users will always be able to repay to prevent being liquidated. Additionally, front-running is not possible on Arbitrum, which makes the attack vector invalid.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering the issue low based on above comments

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [raymondfam](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/243/#issuecomment-1571319950): rejected
