### ISSUE TITLE
deadrxsezzz - Setting `heartbeatInterval` as immutable possesses a risk

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#274]
deadrxsezzz

medium

# Setting `heartbeatInterval` as immutable possesses a risk

## Summary
Currently `heartbeatInterval` is set as an immutable when setting up the Chainlink oracle for a token. This is dangerous as Chainlink can change it and cause malfunction in the contract.

## Vulnerability Detail
As assets become more used and their price is more needed, Chainlink lowers their heartbeats and deviation thresholds. This would especially be the case when speaking about pairs on Arbitrum.
An example would be the pair 'AAVE/USD'. Because it is much more needed and used on Ethereum Mainnet, there it has a 1-hour [heartbeat](https://data.chain.link/ethereum/mainnet/crypto-usd/aave-usd). The same pair on Arbitrum has a 24-hour [heartbeat](https://data.chain.link/arbitrum/mainnet/crypto-usd/aave-usd). As more people projects launch on Arbitrum and use Chainlink Data Feeds, the heartbeats WILL be lowered. Since they are currently immutable project will not be able to change the values and will be prone to using stale data.

## Impact
Project will be prone to using stale data in the future

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/adaptor/chainlinkAdaptor.sol#L28

## Tool used

Manual Review

## Recommendation
Do not use `heartbeatInterval` as immutable. Create a function to change the heartbeat.

**Comment by hrishibhat** [comment]
Not a duplicate of #449. Given the changing of heartbeat can be unlikely, however even in that case a `perpRiskParams` can always be updated with a new adapter.
