### ISSUE TITLE
deadrxsezzz - Uniswap oracle is not advised to be used on L2s

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#275]
deadrxsezzz

medium

# Uniswap oracle is not advised to be used on L2s

## Summary
Uniswap advises developers not to use Uniswap oracle on L2s as price feeds are much easier to be manipulated. 

## Vulnerability Detail
The quoted [statement](https://docs.uniswap.org/concepts/protocol/oracle#oracles-integrations-on-layer-2-rollups) made from the Uniswap team is regarding integration on L2 Optimism, where every transaction is a different block, however, it is also valid for Arbitrum, as the average block time on Arbitrum is ~0.25s.

> ### Oracles Integrations on Layer 2 Rollups
> Optimism
On Optimism, every transaction is confirmed as an individual block. The block.timestamp of these blocks, however, reflect the block.timestamp of the last L1 block ingested by the Sequencer. For this reason, Uniswap pools on Optimism are not suitable for providing oracle prices, as this high-latency block.timestamp update process makes the oracle much less costly to manipulate. In the future, it's possible that the Optimism block.timestamp will have much higher granularity (with a small trust assumption in the Sequencer), or that forced inclusion transactions will improve oracle security. For more information on these potential upcoming changes, please see the [Optimistic Specs repo](https://github.com/ethereum-optimism/optimistic-specs/discussions/23). **For the time being, usage of the oracle feature on Optimism should be avoided.**

## Impact
Easily manipulated oracle prices

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/adaptor/uniswapPriceAdaptor.sol#L49
## Tool used

Manual Review

## Recommendation
Do not use Uniswap's oracle on Arbitrum for the time being.

**Comment by arbitrary-sparrow** [comment]
Escalate for 10 USDC

This issue is not a duplicate of https://github.com/sherlock-audit/2023-04-jojo-judging/issues/281 because it is talking about a completely different topic (TWAP manipulation through increased block throughput).

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This issue is not a duplicate of https://github.com/sherlock-audit/2023-04-jojo-judging/issues/281 because it is talking about a completely different topic (TWAP manipulation through increased block throughput).

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
The issue with optimism is their timestamps used to be incorrect. I don’t believe Arbitrum has that problem. Arbitrum will return their own timestamp and not to synchronized the timestamp of L1

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue low. based on the following comment from the Lead Watson. 
> 1) Only one observation can exist per second due to this line, which invalidates the statement that it is block based:
https://github.com/Uniswap/v3-core/blob/d8b1c635c275d2a9450bd6a78f3fa2484fef73eb/contracts/libraries/Oracle.sol#L90

> 2) It doesn't just add the current price, it's time weighted so 1 observation with a 30 second gap is the same as a 30 obersevations with a 1 second gap, which invalidates the statement about more blocks in 30 minutes than the last 6 hours because that wouldn't matter:
https://github.com/Uniswap/v3-core/blob/d8b1c635c275d2a9450bd6a78f3fa2484fef73eb/contracts/libraries/Oracle.sol#L36-L44

> 3) Even if there was some manipulation, which would be very difficult to achieve unless the user owned the sequencer and was abusing it, there are saveguards in the uniswapPriceAdaptor.sol contract to revert if the price is too far out of bounds.:
https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/adaptor/uniswapPriceAdaptor.sol#L50-L52

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ArbitraryExecution](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/275/#issuecomment-1570553455): accepted
