### ISSUE TITLE
deadrxsezzz - Incompatibility with tokens which do not return `bool` on `.approve`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#278]
deadrxsezzz

high

# Incompatibility with tokens which do not return `bool` on `.approve`

## Summary
DepositStableCoinToDealer.sol FlashLoanLiquidate.sol FlashLoanRepay.sol and GeneralRepay.sol implement IERC20 interface which expects tokens to return a `bool` on `.approve`

## Vulnerability Detail
All 4 contracts have the following line: 
```solidity
IERC20(asset).approve(approveTarget, amount);
```
The IERC20 interface expects a return value from `.approve` which many ERC20 tokens, such as USDT and BNB, do not return.
By the following lines we understand that the project expects to work with USDT
```solidity
        // if usdt
        IERC20(asset).approve(approveTarget, 0);
        IERC20(asset).approve(approveTarget, amount);
```
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/stableCoin/DepositStableCoinToDealer.sol#L33-#L35
Since USDT is an expected token and there are special extra lines of code to implement logic for it, I believe incompatibility with it, should be considered High severity.

## Impact
DepositStableCoinToDealer.sol FlashLoanLiquidate.sol FlashLoanRepay.sol and GeneralRepay.sol  will not be able to work with assets which do not return `bool` on `.approve`

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/stableCoin/DepositStableCoinToDealer.sol#L33-#L35
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/flashloanImpl/FlashLoanLiquidate.sol#L61
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/flashloanImpl/FlashLoanRepay.sol#L43
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/flashloanImpl/GeneralRepay.sol#L43

## Tool used

Manual Review

## Recommendation
use `safeApprove` instead of 'approve'

**Comment by deadrosesxyz** [comment]
Escalate for 10 USDC
I don’t know why this issue is excluded. It describes that the project is incompatible with tokens which do not return value on their ‘.approve’ method. This is common as big tokens such as USDT and BNB do not return values on the said method. The project even expects USDT as it has added special functionalities in order to be usable for USDT. I expect a revaluation.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> I don’t know why this issue is excluded. It describes that the project is incompatible with tokens which do not return value on their ‘.approve’ method. This is common as big tokens such as USDT and BNB do not return values on the said method. The project even expects USDT as it has added special functionalities in order to be usable for USDT. I expect a revaluation.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
@hrishibhat what do you think of this

**Comment by Trumpero** [comment]
This issue doesn't cause any loss, since USDT is not a collateral token. It only affects the `DepositStableCoinToDealer.depositStableCoin()` function and `GeneralRepay.repayJUSD` function that incompatible tokens (such as USDT) are unable for swapping to USDC by these functions. Because users are also able to swap incompatible tokens to USDC themself and deposit/repay afterwards, I believe its impact is low. However, I agree that it shouldn't be excluded and should be fixed.

**Comment by JoscelynFarr** [comment]
Yes agree with that. And there will be an fix review

**Comment by JoscelynFarr** [comment]
fix link
https://github.com/JOJOexchange/smart-contract-EVM/commit/0586bffd27687e62239993932e15ea56e67e8b83
https://github.com/JOJOexchange/JUSDV1/commit/255ef8ee11ceb5eff15a6d5d0e731e600f20dded

**Comment by hrishibhat** [comment]
Result:
Low
Unique
USDT is not listed in the primary tokens used by the protocol. As mentioned by the above comment the code for accommodating USDT seems to be an additional feature to swap for USDC which is the primary token, there is no medium impact of this issue.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [iamjakethehuman](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/278/#issuecomment-1568442172): rejected

**Comment by IAm0x52** [comment]
PRs need to include safeApproval for 0 to keep compatibility

**Comment by IAm0x52** [comment]
Update fixes ([JUSD](https://github.com/JOJOexchange/JUSDV1/commit/5918d68be9b5b021691f768da98df5f712ac6edd) and [EVM](https://github.com/JOJOexchange/smart-contract-EVM/commit/b2384d848fce5ba6247e12fcc18362e2875696c1)) look good. A safeApprove to 0 has been added in all instances.
