### ISSUE TITLE
deadrxsezzz - Project doesn't comply with EIP-20

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#279]
deadrxsezzz

medium

# Project doesn't comply with EIP-20

## Summary
JOJO Exchange is not compliant with EIP-20

## Vulnerability Detail
As stated in the docs, JOJO Exchange is expected to comply with any EIPs
> Q: Is the code/contract expected to comply with any EIPs? Are there specific assumptions around adhering to those EIPs that Watsons should be aware of?
expected to comply with any EIPs

EIP-20 [states](https://eips.ethereum.org/EIPS/eip-20#:~:text=Callers%20MUST%20handle%20false%20from%20returns%20(bool%20success).%20Callers%20MUST%20NOT%20assume%20that%20false%20is%20never%20returned!) that wherever `bool` values are returned, they MUST be handled: 
> Callers MUST handle false from returns (bool success). Callers MUST NOT assume that false is never returned!

Everywhere where `.approve` is used, the value returned is not handled in any way.
```solidity
        IERC20(asset).approve(approveTarget, 0);
        IERC20(asset).approve(approveTarget, amount);
```
Therefore, the code is not EIP-20 compliant, when it is expected to be. 

## Impact
JOJO Exchange doesn't comply with EIP-20, when it is expected to comply with any EIP

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/stableCoin/DepositStableCoinToDealer.sol#L33-#L35
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/flashloanImpl/FlashLoanLiquidate.sol#L61
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/flashloanImpl/FlashLoanRepay.sol#L43
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/flashloanImpl/GeneralRepay.sol#L43

## Tool used

Manual Review

## Recommendation
Check return values from `.approve`

**Comment by deadrosesxyz** [comment]
Escalate for 10 USDC
The project docs state that JOJO is expected to comply with any EIPs. The project does not fully comply with EIP20. Not complying with an EIP when a project states that it should comply with it has historically been validated as Medium Severity Finding.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> The project docs state that JOJO is expected to comply with any EIPs. The project does not fully comply with EIP20. Not complying with an EIP when a project states that it should comply with it has historically been validated as Medium Severity Finding.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
This is to suitable for USDT

**Comment by Trumpero** [comment]
I believe this is low/info for the same reason as #278

**Comment by hrishibhat** [comment]
Result:
Low
Unique
With the given tokens in use, there is no H/M impact to the protocol. Considering this a low issue

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [iamjakethehuman](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/279/#issuecomment-1568427360): rejected
