### ISSUE TITLE
yellowBirdy - Ability to over-withdraw primary enables oracle price manipulation attack, leading to loss of funds and bad debt.

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#283]
yellowBirdy

medium

# Ability to over-withdraw primary enables oracle price manipulation attack, leading to loss of funds and bad debt.

## Summary
`executeWitdarwal()` allows for withdrawing the primary asset to negative when there are open positions in net profit > cumulative maintenanceMargin. Effectively it allows user to realise and withdraw profits (above `maintenanceMargin`) together with ALL of collateral without closing any positions. As such, opening the position to liquidation with guaranteed bad debt. It is dependant solely on the oracle price, thus susceptible to an attack similar to the [GMX AVAX attack ](https://twitter.com/jayantkrish/status/1571893643178569728?s=20&t=O--bs-V1Xnkmzm2JZOdZsw)
## Vulnerability Detail
Consider the following test case in the context of `test/liquidation-test.ts` suite where `liquidationThreshold = 3%` `liquidationPriceOff = 1%`
```typescript
    it("withdraws below zero with open position and liquidates with bad debt", async () => {
      await openPosition(trader1, trader2, "10", "30000", perp0, orderEnv);
      await context.priceSourceList[0].setMarkPrice(utils.parseEther("30945"));
      await context.dealer
        .connect(trader1)
        .requestWithdraw(utils.parseEther("10001"), utils.parseEther("0"));
      await context.dealer
        .connect(trader1)
        .executeWithdraw(trader1.address, false);
      await checkCredit(context, trader1.address, "-1", "0");
      await context.priceSourceList[0].setMarkPrice(utils.parseEther("30000"));

      let operator = trader2;
      await context.dealer
        .connect(liquidator)

        .setOperator(operator.address, true);
      await perp0
        .connect(operator)
        .liquidate(
          liquidator.address,
          trader1.address,
          utils.parseEther("10"),
          utils.parseEther("-297000")
        );
      await checkCredit(context, insurance, "-3151", "0");
      expect(await context.dealer.isSafe(trader1.address)).to.be.true;

    });

```
By moving the price by slightly more than 3% the attacker is able to withdraw more than the full principal of 10K. 
After the price returns to the market value the position gets liquidated with 1% discount. Since there is no more collateral left the loss is taken by the insurance fund. 

In order to execute such an attack, attacker would require significant capital able to move the price by percentage higher than `liquidationThreshold - liquidationPriceOff`.The aforementioned GMXs AVAX perp attack illustrates that it is indeed possible.

## Impact
Loss of primary funds due to overwithdrawal and bad debt.

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/lib/Funding.sol#L152-L157

https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/lib/Liquidation.sol#L119-L124

https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/lib/Liquidation.sol#L53-L85

## Tool used

Manual Review, Hardhat.

## Recommendation

Prevent users from withdrawing primary collateral below certain threshold T. It could be either 
- cumulative liquidation discount + insurance fee at the moment of withdrawal. 
or more conservatively
- the cumulative maintenance margin at moment of opening each position

**Comment by yellowBirdy** [comment]
Escalate for 10 USDC

1. This issue is NOT contingent on a bad oracle choice as illustrated by the GMX AVAX case. 
2. Mitigation does NOT affect *liquidation* logic, but withdrawal logic.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> 1. This issue is NOT contingent on a bad oracle choice as illustrated by the GMX AVAX case. 
> 2. Mitigation does NOT affect *liquidation* logic, but withdrawal logic.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
Hi but our model is based on the order book. 
The opening price is provided by the market maker, so withdrawing USDC will not affect the open price, markPrice is only related to liquidation

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue as low based on Sponsor comment.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yellowBirdy](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/283/#issuecomment-1570007332): rejected
