### ISSUE TITLE
immeas - `JOJODealer` assumes that JUSD is equal to USDC

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#308]
immeas

medium

# `JOJODealer` assumes that JUSD is equal to USDC

## Summary
`JOJODealer` assumes JUSD stays equal to USDC which might not be true. This can cause issues with collateralization of trading positions. 

## Vulnerability Detail

From [docs](https://docs.jojo.exchange/JUSD#what-is-jusd):
> JUSD is a stable coin developed by JOJO system to support multi-collateralization. This features allows users to use other non-stable coin assets (BTC, ETH, etc.) as margin for trading. JUSD works like DAI and users can mint JUSD by staking other ERC20 tokens as collateral. JUSD can be freely traded, however, **its price is not guaranteed to be equal to Primary asset in the open market.**

Now in the code, JUSD is assumed to have a price equal to USDC (primary asset), `_isSafe` as an example:

https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/lib/Liquidation.sol#L100-L102
```solidity
File: smart-contract-EVM/contracts/lib/Liquidation.sol

100:            netPositionValue +
101:                state.primaryCredit[trader] +
102:                SafeCast.toInt256(state.secondaryCredit[trader]) >=
```

If the price of JUSD moves below USDC this can cause issues where traders can open positions that aren't sufficiently covered.

Since you win primary credit:
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/lib/Position.sol#L27
```solidity
File: smart-contract-EVM/contracts/lib/Position.sol

27:        state.primaryCredit[trader] += pnl;
```
This can be used to trade the now less valuable JUSD for USDC.

## Impact
If the price of JUSD changes, mainly if it falls below USDC, it could cause problems with how positions are collateralized. Since a trader could open a position against less valuable JUSD and close it, winning USDC.

There are some issues describing how a depeg of JUSD might happen:
- [unborrowed JUSD are stuck in `JUSDBank`](https://github.com/sherlock-audit/2023-04-jojo-0ximmeas/issues/2)
- [potential economic issues with JUSD](https://github.com/sherlock-audit/2023-04-jojo-0ximmeas/issues/4)
- [`JUSDBank::handleBadDept` can be dangerous](https://github.com/sherlock-audit/2023-04-jojo-0ximmeas/issues/9)
- [`JOJOBank::handleBadDept` can be front run with dust to keep debt bad](https://github.com/sherlock-audit/2023-04-jojo-0ximmeas/issues/10)

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/lib/Liquidation.sol#L100-L102

https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/lib/Liquidation.sol#L121-L123

https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/lib/Liquidation.sol#L142-L143

## Tool used
Manual Review

## Recommendation
Either you need to track the price of JUSD/USDC. Or a way to freeze JUSD as collateral, that might make a lot of positions under water though.

**Comment by 0ximmeas** [comment]
Escalate for 10 USDC

I don't believe this is a duplicate of https://github.com/sherlock-audit/2023-04-jojo-judging/issues/417

https://github.com/sherlock-audit/2023-04-jojo-judging/issues/417 addresses the problem of that JUSD is pegged to USDC if USDC loses its peg to USD.

This issue is about that JUSD might lose its peg to USDC. And in that case, the JOJODealer market can be abused since it assumes JUSD and USDC to be 1:1. The protocol documentation also mentions that the 1:1 peg between JUSD and USDC is not guaranteed, hence there should also be some safety mechanism in the JOJODealer market to protect against a depeg against USDC.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I don't believe this is a duplicate of https://github.com/sherlock-audit/2023-04-jojo-judging/issues/417
> 
> https://github.com/sherlock-audit/2023-04-jojo-judging/issues/417 addresses the problem of that JUSD is pegged to USDC if USDC loses its peg to USD.
> 
> This issue is about that JUSD might lose its peg to USDC. And in that case, the JOJODealer market can be abused since it assumes JUSD and USDC to be 1:1. The protocol documentation also mentions that the 1:1 peg between JUSD and USDC is not guaranteed, hence there should also be some safety mechanism in the JOJODealer market to protect against a depeg against USDC.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
JUSD will always be equal to USDC in the perpetual contract trading system

**Comment by Trumpero** [comment]
This issue is similar with #127, and should be invalid

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique 
Considering this a non-issue based on above comments.
Additional sponsor comment:
> In our system, JUSD's value is assuming as same as USDC. And the usage of JUSD is to using as trading margin

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0ximmeas](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/308/#issuecomment-1571656155): accepted
