### ISSUE TITLE
immeas - unborrowed JUSD are stuck in `JUSDBank`

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#309]
immeas

medium

# unborrowed JUSD are stuck in `JUSDBank`

## Summary
Unborrowed JUSD will pile up in `JUSDBank` giving a false total supply. This might give a false impression of the value of the coin and cause it to be valued lower than USDC.

## Vulnerability Detail
JUSD can be let into the market in two ways:
Either by `borrow` JUSD in `JUSDBank`:

https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBank.sol#L292
```solidity
File: JUSDV1/src/Impl/JUSDBank.sol

292:            IERC20(JUSD).safeTransfer(to, tAmount);
```

or by buying JUSD for USDC in `JUSDExchange`:

https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDExchange.sol#L41-L46
```solidity
File: JUSDV1/src/Impl/JUSDExchange.sol

41:    function buyJUSD(uint256 amount, address to) external {
42:        require(isExchangeOpen, JUSDErrors.NOT_ALLOWED_TO_EXCHANGE);
43:        IERC20(primaryAsset).safeTransferFrom(msg.sender, owner(), amount);
44:        IERC20(JUSD).safeTransfer(to, amount);
45:        emit BuyJUSD(amount, to, msg.sender);
46:    }
```

But when you repay you transfer the JUSD back to `JUSDBank`:

https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBank.sol#L325
```solidity
File: JUSDV1/src/Impl/JUSDBank.sol

325:        IERC20(JUSD).safeTransferFrom(payer, address(this), tBorrowAmount);
```

Since there  is no way of pulling JUSD out of `JUSDBank` other than borrowing there is a possibility of it piling up there. Since it can be bought in the `JUSDExchange` and returned to `JUSDBank` there will be a net influx of JUSD to `JUSDBank` which cannot be removed from it.

Since it is stuck there when it is not borrowed a look at TVL in the bank compared to total value of JUSD will give an unfair view. This could cause JUSD to lose its peg to USDC.

## Impact
A false total market value might devalue JUSD causing it to be worth less than a USDC. This would cause further [issues](https://github.com/sherlock-audit/2023-04-jojo-0ximmeas/issues/1) in `JOJODealer` as it relies on JUSD and USDC being 1:1.

## Code Snippet
See above

## Tool used
Manual Review

## Recommendation
Returned JUSD must be burnt, since otherwise there will be non collateral backed JUSD which would affect the price.

Duplicate of #306

**Comment by 0ximmeas** [comment]
Escalate for 10 USDC

I believe this rather is a duplicate of https://github.com/sherlock-audit/2023-04-jojo-judging/issues/306 since this issue also addresses the lack of burn mechanism that could cause issues for the protocol.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I believe this rather is a duplicate of https://github.com/sherlock-audit/2023-04-jojo-judging/issues/306 since this issue also addresses the lack of burn mechanism that could cause issues for the protocol.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
agree with that

**Comment by hrishibhat** [comment]
Result: 
Medium
Duplicate of #306

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0ximmeas](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/{self.issue_number}/#issuecomment-{self.comment_id}): accepted
