### ISSUE TITLE
branch_indigo - Key JUSD Global and Reserve Setting Update not Checked/Reverted Leading to Premature Liquidations

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#329]
branch_indigo

medium

# Key JUSD Global and Reserve Setting Update not Checked/Reverted Leading to Premature Liquidations

## Summary
In JUSD, global and reserve setting such as borrowFeeRate, InitialMortgageRate and liquidationMortgageRate are not checked when initialized or updated, creating risks of premature liquidations of maximized borrowers.
## Vulnerability Detail
All three variables above can be set and updated in JOJOOperation.sol but their values are not sufficiently checked during updates.

InitialMortgageRate is part of a reserve setting, a ratio that determines the maximum borrow amount given total collateral value.  liquidationMortgageRate is also reserve specific, a ratio of total collateral value as maximum debt a borrower can accumulate at any given time before considered liquidatable. borrowFeeRate is a global variable, a rate at which debt interests accumulate.

There should be some constraints on the relations between the three to ensure safety of a borrower who maximizes their borrow amount. 
(1) InitialMortgageRate < LiquidationMortgageRate: This needs to give enough room for borrow debts to grow with interests and also allow for price fluctuation. 
(2)borrowFeeRate needs to be proportional or soft-capped depending on the difference between LiquidationMortgageRate and InitialMortgageRate, so that debt interests wouldn't grow too fast that cause debt quickly outgrows liquidation threshold without change in collateral value.

In addition, since borrowFeeRate is a global variable applying to all reserves, the update of borrowFeeRate overtime should take extra caution to always account for the reserve with the most limiting settings on mortgage rates.

However, the constraints above are not enforced or checked in `initReserve`, `updateRiskParam`, `updateReserveParam` and `updateBorrowFeeRate` in JUSDOperation.sol.

In `initReserve` and `updateRiskParam`, only liquidationPriceOff(a discount for liquidation) and InsuranceFee  are checked in a require statement. Even though liquidationMortgageRate is included, it's isolated from initialMortgageRate and borrowFeeRate, and is only enforcing that the discounts for liquidators and insurance fee are not set too high. 
```solidity
  require(
            JOJOConstant.ONE - _liquidationMortgageRate >
                _liquidationPriceOff +
                    (JOJOConstant.ONE - _liquidationPriceOff).decimalMul(
                        _insuranceFeeRate
                    ),
            JUSDErrors.RESERVE_PARAM_ERROR
        );
```
Furthermore, initialLiquidationMortgageRate and liquidationMortgageRate can be updated separately with no checks which increases risks of error. In `updateReserveParam`,  initialMortgageRate can be updated based on business needs with no checks to ensure that existing liquidationMortgageRate is still sufficiently greater than initialMortgageRate. As an example, if a subsequent update of initialLiquidationMortgageRate equals existing liquidationMortgageRate, all new maximized borrows thereafter can be almost instantly liquidatable as their debt interests accumulate.

```solidity
        reserveInfo[collateral].initialMortgageRate = _initialMortgageRate;
```

Also, borrowFeeRate can be updated separately with no check in `updateBorrowFeeRate`. This means that if borrowFeeRate needs to be increased later on, there is no safe guard or a soft cap. An existing reserve with liquidationMortgageRate set relatively too close to initialLiquidationMortgageRate might risk have all debts with maximized borrows being liquidated within a short period of time.

```solidity
    function updateBorrowFeeRate(uint256 _borrowFeeRate) external onlyOwner {
        t0Rate = getTRate();
        lastUpdateTimestamp = uint32(block.timestamp);
        borrowFeeRate = _borrowFeeRate;
        emit UpdateBorrowFeeRate(_borrowFeeRate, t0Rate, lastUpdateTimestamp);
    }
```
[Here's a test to show unsafe variables results in a premature liquidation. ](https://gist.github.com/bzpassersby/3aaf06271af160f0283fd7998aeed0c3)

## Impact
A later update of any of the three variables mentioned above is not checked or properly reverted, leading to increasing risks of unsafe reserve and global parameters result in maximized borrows liquidated prematurely. 
## Code Snippet
[https://github.com/JOJOexchange/JUSDV1/blob/011e10d36257a404c8c1d7d2b8c9f01a2b7a1969/src/Impl/JUSDOperation.sol#L70-L77](https://github.com/JOJOexchange/JUSDV1/blob/011e10d36257a404c8c1d7d2b8c9f01a2b7a1969/src/Impl/JUSDOperation.sol#L70-L77)

[https://github.com/JOJOexchange/JUSDV1/blob/011e10d36257a404c8c1d7d2b8c9f01a2b7a1969/src/Impl/JUSDOperation.sol#L168-L173](https://github.com/JOJOexchange/JUSDV1/blob/011e10d36257a404c8c1d7d2b8c9f01a2b7a1969/src/Impl/JUSDOperation.sol#L168-L173)

[https://github.com/JOJOexchange/JUSDV1/blob/011e10d36257a404c8c1d7d2b8c9f01a2b7a1969/src/Impl/JUSDOperation.sol](https://github.com/JOJOexchange/JUSDV1/blob/011e10d36257a404c8c1d7d2b8c9f01a2b7a1969/src/Impl/JUSDOperation.sol#L203-L215)

## Tool used

Manual Review

## Recommendation
Add additional check to ensure liquidationMortgageRate is sufficiently greater than initialMortgageRate based on an anticipated maximum borrowFeeRate the protocol might allows. Also add checks to ensure borrowFeeRate is always reasonable per reserve settings.

**Comment by bzpassersby** [comment]
Escalate for 10 USDC
This should be a valid Medium, based on the judging for #408. In both submissions, the insufficient check on `liquidationMortageRate` and `initialMortageRate` is cited as a key vulnerability. Also, premature liquidation is mentioned in both submissions as a potential impact. In this submission, the same function`updateReserveParam` is detailed as part of the code path for the vulnerability.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> This should be a valid Medium, based on the judging for #408. In both submissions, the insufficient check on `liquidationMortageRate` and `initialMortageRate` is cited as a key vulnerability. Also, premature liquidation is mentioned in both submissions as a potential impact. In this submission, the same function`updateReserveParam` is detailed as part of the code path for the vulnerability.  

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
This is trusted admin input validation, considering this issue valid low

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [bzpassersby](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/{self.issue_number}/#issuecomment-{self.comment_id}): rejected
