### ISSUE TITLE
unrealcake - Funding rates of all perpetuals can be crippled and make asset prices excessively volatile

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#333]
unrealcake

high

# Funding rates of all perpetuals can be crippled and make asset prices excessively volatile

## Summary
The `updateFundingRate()` logic can make arbitrage too accessible and also make asset prices excessively volatile

## Vulnerability Detail

Relevant parts of the logic:

- If funding rate for a perpetual exceeds a certain amount, `updateFundingRate()` will revert.
``require(
                (rateList[i] - oldRate).abs() <= maxChange,
                "FUNDING_RATE_CHANGE_TOO_MUCH"
            );``

- This revert applies to all perpetuals in the JOJO exchange, not only the offending perp. 

I understand the require statement is a feature designed to prevent funding rate abuse, and will prevent a variety of attacks under normal circumstances. However when a coin is heavily speculated on, its funding rate can easily exceed a limit that would normally be appropriate. 

I provide one scenario which can stop funding rate for changing for some time and cause excessive price volatilty.

### A highly speculative event in crypto moves funding rates too quickly
Suppose JOJO was available around the LUNA debacle and LUNA was listed.

On Binance, the LUNA/USDT perpetual contract had a funding rate of 0.01% at 12:00 UTC on December 4, 2021, but it spiked to 0.17% at 16:00 UTC and then dropped to -0.15% at 20:00 UTC. That's a 17x followed by nearly 100x change in funding rate. By comparison a number from 1-5 is given as a reference multiplier in the comments.

#### Explaining how funding arbitrage works
Assume that users on JOJO would speculate in a similar pattern to Binance at the time and funding rates would move at a similar rate. After 8 hours we have a 15x change in funding rate causing the `require()` statement to revert with "FUNDING_RATE_CHANGE_TOO_MUCH", and will be left with funding rates of:
Binance: -0.15%
JOJO: 0.01%
Assume market sentiment is growing in this negative funding rate direction on Binance and the rates are going to remain extremely negative or go down even more. For the next 8 hours, a user could go short on JOJO (the "borrowing" leg) and long the same amount on Binance (the "lending" leg), profiting 0.14% before transaction fees. 

#### Damage caused
A user could profit the difference in funding rates by going long/short the "borrowing" leg in JOJO and taking the opposite side with the "lending" leg on Binance. When users are incentivized to do this on JOJO, a positive feedback loop is created [^1] and JOJO's calculated change in funding rate is further increased, exacerbating the problem because `updateFundingRate()` will keep reverting for the offending perp and every other perp.

Taking this a step further, when "every other perp" is prevented from updating their funding rate, some more arbitrage opportunities can also present themselves, where there would be none if funding rate was free to change! Suppose these opportunities are in "normal" markets without any impetus like LUNA. In this case market forces would bring rates in the other exchange (not JOJO) back to 0.01% or whatever the reference rate is. The longer funding rates across the board remain crippled, the more chances there are for a new funding arb opportunity to arise. It is possible for one major market event to produces numerous aftershocks in the JOJO protocol funding mechanism, crippling it for even longer.

At some point in time, an equilibrium will be established. Because funding rate cannot move, price will move instead. And that is why prices will be excessively volatile relative to the broad market.

[^1]: Positive feedback loop is created because the "borrowing" leg has two properties. It follows overall sentiment in a market, being an imbalance in longs or shorts. It also is the direction that a profitable arb will result in. Incentives are skewed in this direction and without any other market impetuses there is no reason for funding rate to go back to normal.

## Impact
The funding mechanism will no longer serve its intended purpose of keeping perpetual contracts close to spot price.

## Code Snippet

https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/fundingRateKeeper/FundingRateUpdateLimiter.sol#L37-L56

## Tool used

Manual Review

## Recommendation

Allow a perp's funding rate to change by the amount `maxChange` instead of reverting the whole `updateFundingRate()` call.

**Comment by RLSoftwareDev** [comment]
Escalate for 10 USDC
I cited the LUNA debacle as an example to show that funding rates can and will exceed expectations.

An owner can modify maximum change in funding rate, but:
What if it's too late - owner goes on holiday for a week? Will the owner know what an appropriate change in funding rate is, when the market is moving so fast? The whole protocol is at reputational risk due to human error.

And suppose owner sets maximum change in funding rate to account for a LUNA-like situation: 100x - then the problems that this mechanism was intended to prevent are now possible. In addition, when a situation worse than LUNA comes around, we will get the same scenario I have outlined above.

Even if the owner has free reign to modify maximum change in funding rate, it is still possible for my scenario to happen.
Here's an example:

Binance: -0.15%
JOJO: 0.01%

Arb trade is long on Binance, short on JOJO. Theoretical funding rate on JOJO wants to change by 15x, so `updateFundingRate()` reverts and so JOJO funding rate is unchanged

Binance: -0.3%
JOJO: 0.01%

Owner detects the issue and now sets funding rate change multiplier to 100x. Sounds like its a decent amount right? Since Binance is only -0.3% right now.
JOJO has a smaller market so less money is needed to change the theoretical funding rate. With the market-wide sentiment being on the short side, AND profitable arb also being on the short side, it is plausible that the funding rate now wants to go to -5%, a 500x change, in which case `updateFundingRate()` will revert again.

Binance: -0.5%
JOJO: 0.01%

We are left with this situation

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> I cited the LUNA debacle as an example to show that funding rates can and will exceed expectations.
> 
> An owner can modify maximum change in funding rate, but:
> What if it's too late - owner goes on holiday for a week? Will the owner know what an appropriate change in funding rate is, when the market is moving so fast? The whole protocol is at reputational risk due to human error.
> 
> And suppose owner sets maximum change in funding rate to account for a LUNA-like situation: 100x - then the problems that this mechanism was intended to prevent are now possible. In addition, when a situation worse than LUNA comes around, we will get the same scenario I have outlined above.
> 
> Even if the owner has free reign to modify maximum change in funding rate, it is still possible for my scenario to happen.
> Here's an example:
> 
> Binance: -0.15%
> JOJO: 0.01%
> 
> Arb trade is long on Binance, short on JOJO. Theoretical funding rate on JOJO wants to change by 15x, so `updateFundingRate()` reverts and so JOJO funding rate is unchanged
> 
> Binance: -0.3%
> JOJO: 0.01%
> 
> Owner detects the issue and now sets funding rate change multiplier to 100x. Sounds like its a decent amount right? Since Binance is only -0.3% right now.
> JOJO has a smaller market so less money is needed to change the theoretical funding rate. With the market-wide sentiment being on the short side, AND profitable arb also being on the short side, it is plausible that the funding rate now wants to go to -5%, a 500x change, in which case `updateFundingRate()` will revert again.
> 
> Binance: -0.5%
> JOJO: 0.01%
> 
> We are left with this situation
> 
> 
>  
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
In fact, we will calculate the `fundingRate` at the back end before setting on the chain. We apply the same set of fundingRate calculation rules at the entire product level. I would like to ask if you are worried that a certain perpetual market will exceed maxChange when setting on the chain and cause a revert?

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Given that this is related to an admin function being able to set necessary parameters, considering this a low based on the above comments.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [unrealcake](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/333/#issuecomment-1569097479): rejected
