### ISSUE TITLE
RaymondFam - JOJOFlashLoan() in FlashLoanLiquidate.sol and FlashLoanRepay.sol does not check if the collateral isn’t USDC before swapping to USDC

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#334]
RaymondFam

medium

# JOJOFlashLoan() in FlashLoanLiquidate.sol and FlashLoanRepay.sol does not check if the collateral isn’t USDC before swapping to USDC

## Summary
The collateral asset can be anything (ETH, BTC, USDC etc)  which registers in the system. Unlike GeneralRepay.sol, a check if `asset != USDC` is not implemented prior to swapping the collateral asset to USDC.

## Vulnerability Detail
If asset were to equal USDC in these contracts, the contracts would attempt to swap USDC for USDC. Depending on the specific implementation of the swapTarget contract, this could have a few different outcomes:

1. If the swap contract is designed to handle this gracefully, then the swap would essentially have no effect. The contract would still pay any associated gas costs for the swap operation, but the state of the contract wouldn't change.

2. If the swap contract isn't designed to handle this case, then it could potentially revert the transaction. This would prevent `JOJOFlashLoan()` from completing successfully.

## Impact
In a worst-case scenario, if the swap contract is designed poorly, it could potentially result in a loss of funds. This would be a significant security issue, but it's also highly unlikely if the swap contract is implemented correctly.

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/flashloanImpl/FlashLoanLiquidate.sol#L52-L70
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/flashloanImpl/FlashLoanRepay.sol#L41-L52

## Tool used

Manual Review

## Recommendation
Consider including a check for `asset != USDC` prior to attempting the swap, similar to what's done in the `GeneralRepay` contract. This would prevent unnecessary operations and potential issues if `USDC` is passed as the asset parameter.

**Comment by raymondfam** [comment]
Escalate for 10 USDC

If the asset is indeed USDC, this action is unnecessary and could lead to undesirable outcomes, ranging from wasted gas to failed transactions, or in a worst-case scenario, potential loss of funds if the swap contract is poorly implemented.

Although the impact could vary based on the design of the swap contract, it's good coding practice to account for unnecessary operations via a simple check.

In the interest of creating robust, resilient and efficient smart contracts, it's worth addressing this finding to prevent the  potential pitfalls. This change could lead to a more efficient and reliable system, providing users with a more consistent experience.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> If the asset is indeed USDC, this action is unnecessary and could lead to undesirable outcomes, ranging from wasted gas to failed transactions, or in a worst-case scenario, potential loss of funds if the swap contract is poorly implemented.
> 
> Although the impact could vary based on the design of the swap contract, it's good coding practice to account for unnecessary operations via a simple check.
> 
> In the interest of creating robust, resilient and efficient smart contracts, it's worth addressing this finding to prevent the  potential pitfalls. This change could lead to a more efficient and reliable system, providing users with a more consistent experience.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
Hi, we will not use USDC as collateral

**Comment by Trumpero** [comment]
It is a low/info issue and I believe it is unnecessary to fix

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue low based on the above comments.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [raymondfam](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/334/#issuecomment-1571300498): rejected
