### ISSUE TITLE
igingu - JUSDV1 - There is no mechanism for taking JUSD out of JUSDBank and refunding it with the JUSDExchange

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#347]
igingu

high

# JUSDV1 - There is no mechanism for taking JUSD out of JUSDBank and refunding it with the JUSDExchange

## Summary
JUSD can be minted/burned by JUSD token's owner. JoJo team plans to mint JUSD and send it to JUSDBank, for users to take loans by depositing collateral. Each JUSD loan has an interest rate, such that the user needs to pay back more than they borrowed, making a profit for the platform's owners as well.

## Vulnerability Detail
Every time someone repays a loan, or a positions gets liquidated, JUSD is sent to the JUSDBank contract. There is no functionality to take out JUSD from the bank, or to refund excess JUSD in the JUSDExchange.

## Impact
JUSD will keep piling up in JUSDExchange, and interest gained from lending will be stuck there as well. There should be a mechanism for platform team to take the interest out of the JUSDExchange, or at least burn the JUSD from time to time, when it is not needed.

JUSDExchange should also have a way to send JUSD to it, and receive back the primary asset. 

I discussed this with the platform team (@Joscelyn), and this was their response: **"Hi after internal discussion, the interface for refundJusD is missing. And we will add it, you could submit it"**

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDExchange.sol#L41

## Tool used

Manual Review

## Recommendation
Mentioned above.

Duplicate of #306

**Comment by igingu** [comment]
Escalate for 10 USDC
I think this should be a duplicate of #306 , not #398. It has to do with JUSD piling up, without any mechanism for burning or refunding it. It is basically the same submission as #306

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> I think this should be a duplicate of #306 , not #398. It has to do with JUSD piling up, without any mechanism for burning or refunding it. It is basically the same submission as #306 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> I think this should be a duplicate of #306 , not #398. It has to do with JUSD piling up, without any mechanism for burning or refunding it. It is basically the same submission as #306 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
agree with that

**Comment by hrishibhat** [comment]
Escalation accepted

Valid duplicate of #306

**Comment by sherlock-admin** [comment]
> Escalation accepted
> 
> Valid duplicate of #306 

    This issue's escalations have been accepted!

    Contestants' payouts and scores will be updated according to the changes made on this issue.
