### ISSUE TITLE
Ace-30 - Smart contract EVM: Malicious user can prevent liquidation by openning lots of positions due to gas limit

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#348]
Ace-30

high

# Smart contract EVM: Malicious user can prevent liquidation by openning lots of positions due to gas limit

## Summary
to liquidate an account one should call requestLiquidation()

- requestLiquidation() calls getLiquidateCreditAmount()
- getLiquidateCreditAmount() calls _isSafe()
- _isSafe() calls getTotalExposure()
- getTotalExposure() goes through all openPositions of trader
```solidity
    function getTotalExposure(Types.State storage state, address trader)
        public
        view
        returns (
            int256 netPositionValue,
            uint256 exposure,
            uint256 maintenanceMargin
        )
    {
        // sum net value and exposure among all markets
        for (uint256 i = 0; i < state.openPositions[trader].length; ) { 
            (int256 paperAmount, int256 creditAmount) = IPerpetual(
                state.openPositions[trader][i]
            ).balanceOf(trader);
            Types.RiskParams storage params = state.perpRiskParams[
                state.openPositions[trader][i]
            ];
            int256 price = SafeCast.toInt256(
                IMarkPriceSource(params.markPriceSource).getMarkPrice()
            );

            netPositionValue += paperAmount.decimalMul(price) + creditAmount;
            uint256 exposureIncrement = paperAmount.decimalMul(price).abs();
            exposure += exposureIncrement;
            maintenanceMargin +=
                (exposureIncrement * params.liquidationThreshold) /
                Types.ONE;

            unchecked {
                ++i;
            }
        }
    }
```

So a malicious user can add enough positions so that the gas of liquidation transaction reaches the gas limit of a block and always revert.

## Impact
Malicious user can prevent liquidation by openning lots of positions due to gas limit

## Code Snippet
https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Liquidation.sol#L53-L85
## Tool used

Manual Review

## Recommendation
put a limit on total number of open positions for each user

**Comment by imp0wd3r** [comment]
Escalate for 10 USDC
The development team has clearly stated that the DoS caused by too many perpetuals is a known issue.

> Q: Please list any known issues/acceptable risks that should not result in a valid finding.
> 12.DOS attack possible for trading:
> b. _realizePnl function loops over an unbounded array within the openPositions
mapping, but there is a limit on the number of registered perpetuals to avoid
reaching the block gas limit.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> The development team has clearly stated that the DoS caused by too many perpetuals is a known issue.
> 
> > Q: Please list any known issues/acceptable risks that should not result in a valid finding.
> > 12.DOS attack possible for trading:
> > b. _realizePnl function loops over an unbounded array within the openPositions
> mapping, but there is a limit on the number of registered perpetuals to avoid
> reaching the block gas limit.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by securitygrid** [comment]
Escalate for 10 USDC
this issue is similar as #47. They have the same root, due to opening too many positions. So two issues should be merged.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> this issue is similar as #47. They have the same root, due to opening too many positions. So two issues should be merged.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by arbitrary-cr0** [comment]
Escalate for 10 USDC
This issue is invalid because it mistakes what a position represents. A position held by a user represents the total value of options that a user is trading for a specific perpetual. The value stored in the `openPositions` array for a trader is the address of the perpetual. It should not be possible for the perpetual address to exist more than once in the `openPositions` array for a trader.

If a position were to exist more than once in a trader's array, this would mean when calculating their net value and exposure to determine liquidation, it would be double counted, which is wrong.

**Comment by arbitrary-sparrow** [comment]
Escalate for 10 USDC

Reposting @arbitrary-cr0 so it gets picked up by the bot:

This issue is invalid because it mistakes what a position represents. A position held by a user represents the total value of options that a user is trading for a specific perpetual. The value stored in the `openPositions` array for a trader is the address of the perpetual. It should not be possible for the perpetual address to exist more than once in the `openPositions` array for a trader.

If a position were to exist more than once in a trader's array, this would mean when calculating their net value and exposure to determine liquidation, it would be double counted, which is wrong.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Reposting @arbitrary-cr0 so it gets picked up by the bot:
> 
> This issue is invalid because it mistakes what a position represents. A position held by a user represents the total value of options that a user is trading for a specific perpetual. The value stored in the `openPositions` array for a trader is the address of the perpetual. It should not be possible for the perpetual address to exist more than once in the `openPositions` array for a trader.
> 
> If a position were to exist more than once in a trader's array, this would mean when calculating their net value and exposure to determine liquidation, it would be double counted, which is wrong.
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
yes,  The value stored in the openPositions array for a trader is the address of the perpetual.

**Comment by Trumpero** [comment]
Agree with all escalations. This issue should be invalid since the protocol considered it a known issue in the contest docs.

**Comment by hrishibhat** [comment]
Result:
Low 
Has duplicates 

Given that unbounded array over openPositions is a known issue and the fact that the value stored in the openPositions array for a trader is the address of the perpetual, considering this issue as low

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [imp0wd3r](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/348/#issuecomment-1568461277): accepted
- [securitygrid](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/348/#issuecomment-1568649251): accepted
- [ArbitraryExecution](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/348/#issuecomment-1570555391): accepted

**Comment by IAm0x52** [comment]
Fix looks good. Position.sol now enforces a max number of positions
