### ISSUE TITLE
ast3ros - Ineffective heartbeat checking due to inconsistent heartbeat intervals for Oracle price feeds

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#363]
ast3ros

medium

# Ineffective heartbeat checking due to inconsistent heartbeat intervals for Oracle price feeds

## Summary

Different pairs of tokens have different heartbeat intervals for their Oracle price feeds. Using the same `heartbeatInterval` to check two tokens may lead to ineffective or always reverting when getting prices.

## Vulnerability Detail

In `ChainlinkExpandAdaptor` and `JOJOOracleAdaptor` contracts, the `updatedAt` variable is checked with `heartbeatInterval` to ensure that the price is updated timely. The heartbeatInterval is usually set to `86400s` (24 hours).

        require(block.timestamp - updatedAt <= heartbeatInterval, "ORACLE_HEARTBEAT_FAILED");
        require(block.timestamp - USDCUpdatedAt <= heartbeatInterval, "USDC_ORACLE_HEARTBEAT_FAILED");

However, different pairs of tokens may have different heartbeat intervals. For example:
- ETH / USD: 86400s - https://data.chain.link/arbitrum/mainnet/crypto-usd/eth-usd
- BTC / USD: 86400s - https://data.chain.link/arbitrum/mainnet/crypto-usd/btc-usd
- LINK / USD: 3600s - https://data.chain.link/arbitrum/mainnet/crypto-usd/link-usd
- COMP / USD: 3600s - https://data.chain.link/arbitrum/mainnet/crypto-usd/comp-usd
- USDC / USD: 86400s - https://data.chain.link/arbitrum/mainnet/stablecoins/usdc-usd

For example regarding the Perpetual LinkUSDC contract, if in the `ChainlinkExpandAdaptor` for the LINK and USDC pair, 
- if the `heartbeatInterval` is set to 86400s, the checking will be useless for LINK pricefeed since its heartbeat is 3600s.
- if the `heartbeatInterval` is set to 3600s, the getMarkPrice() function will be reverted because USDC has heartbeat of 86400s

For example, in the Perpetual LinkUSDC contract, if the `ChainlinkExpandAdaptor` for the LINK and USDC pair uses the same `heartbeatInterval`:
- If the heartbeatInterval is set to 86400s, the check for LINK price feed will be useless since its heartbeat is 3600s.
- If the heartbeatInterval is set to 3600s, the `getMarkPrice()` function will fail because USDC has a heartbeat of 86400s.

Using the same variable `heartbeatInterval` to check for both price feeds does not work.

## Impact

The price results from Oracle in function `getMarkPrice()` may return stale or incorrect prices or always revert.

## Code Snippet

https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/adaptor/chainlinkAdaptor.sol#L28
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/adaptor/chainlinkAdaptor.sol#L48-L52
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/oracle/JOJOOracleAdaptor.sol#L16
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/oracle/JOJOOracleAdaptor.sol#L31-L32

## Tool used

Manual Review

## Recommendation

Use different `heartbeatInterval` for each token in the Oracle adapter contract.

Duplicate of #449

**Comment by thangtranth** [comment]
Escalate for 10 USDC.

Please recheck and review the example in my analysis. The issue is that using the same `heartbeatInterval` for two token pairs may make it ineffective.

And also this issue is not a duplicate of https://github.com/sherlock-audit/2023-04-jojo-judging/issues/274
The issue 274 mentioned about setting heartbeatInterval as immutable, which is a different thing.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> Please recheck and review the example in my analysis. The issue is that using the same `heartbeatInterval` for two token pairs may make it ineffective.
> 
> And also this issue is not a duplicate of https://github.com/sherlock-audit/2023-04-jojo-judging/issues/274
> The issue 274 mentioned about setting heartbeatInterval as immutable, which is a different thing.
> 
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #449 
This is a valid issue addressed in #449

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [thangtranth](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/363/#issuecomment-1568675807): accepted
