### ISSUE TITLE
ast3ros - Users cannot borrow in the JUSDBank and buy JUSD in JUSDExchange when JUSDBank and JUSDExchange run out of JUSD

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#365]
ast3ros

medium

# Users cannot borrow in the JUSDBank and buy JUSD in JUSDExchange when JUSDBank and JUSDExchange run out of JUSD

## Summary

JUSD is transferred into JUSDBank and JUSDExchange by the owner of JUSD token contract. If the JUSDBank and JUSDExchange run out of JUSD, users cannot borrow JUSD in bank or buy JUSD in exchange.

## Vulnerability Detail

When a user borrows or buy JUSD, JUSD is transferred from JUSDBank / JUSDExchange to the user address.

        IERC20(JUSD).safeTransfer(to, tAmount);

https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBank.sol#L292
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDExchange.sol#L44

If the JUSDBank or JUSDExchange runs out of JUSD or has a JUSD balance less than the amount, the function will revert. To avoid this case, when a user borrows or buys, the JUSD should be minted directly to the user account. This also improves the decentralization since the minting and burning are done by the code instead of the owner who can mint and burn unlimited amount and has to track the balance of JUSD bank/exchange and transfer to the bank/exchange contract when the JUSD balance is low.

## Impact

The borrow function of JUSDBank and buy function of JUSDExchange are disabled.

## Code Snippet

https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBank.sol#L292
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDExchange.sol#L44

## Tool used

Manual Review

## Recommendation

When a user borrows in bank or buys in exchange, mint JUSD directly to the user account instead of transferring the token from JUSD bank to the user account.

Duplicate of #395

**Comment by thangtranth** [comment]
Escalate for 10 USDC.

The issue is that the `borrow` function of JUSDBank and the `buy` function of JUSDExchange are halted when the JUSD balance in both contracts runs out. They have to wait for someone to refill the balance to resume. The protocol assumes that there is always JUSD balance in both contracts, but this assumption is not valid.

The solution is to mint and burn JUSD directly to/from user accounts when they borrow/repay, instead of relying on the contract balances.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> 
> The issue is that the `borrow` function of JUSDBank and the `buy` function of JUSDExchange are halted when the JUSD balance in both contracts runs out. They have to wait for someone to refill the balance to resume. The protocol assumes that there is always JUSD balance in both contracts, but this assumption is not valid.
> 
> The solution is to mint and burn JUSD directly to/from user accounts when they borrow/repay, instead of relying on the contract balances.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
Hi In the mode you mentioned, it is too insecure for the protocol, we have no control over how much JUSD is issued

**Comment by hrishibhat** [comment]
Result:
Low
Duplicate of #395 
Considering this issue a low based on sponsor comment as this is protocol design

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [thangtranth](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/365/#issuecomment-1568700717): rejected
