### ISSUE TITLE
yixxas - `reserve.totalDepositAmount` is shared across all collaterals despite them having very different values

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#380]
yixxas

medium

# `reserve.totalDepositAmount` is shared across all collaterals despite them having very different values

## Summary
Supported collaterals for deposits are WBTC, WETH, ARB. These tokens have extremely different values and should not share the same weightage when it is being added to `reserve.totalDepositAmount`.
1 WBTC is currently worth about 27000x more than 1 ARB. 

## Vulnerability Detail

In `_deposit()` there are 2 kinds of limits enforced by the protocol. A per account limit and a global limit. The per account limit tracks `user.depositBalance[collateral]`. This value is compared to `reserve.maxDepositAmountPerAccount`. `reserve.maxDepositAmountPerAccount` is a value used to decide the maximum of each collateral a user can deposit. This value is however shared across all collaterals. 

The protocol, for instance, may set `reserve.maxDepositAmountPerAccount = 1000e18`. This is a very generous limit for say, WBTC as the USD market value is about $27000000 at the point of this writing. However, the same limit is used for ARB, which is only about $1100.

Similarly, we see that `reserve.totalDepositAmount += amount`. `amount` can be the value of either WBTC, WETH, or ARB, all of which have very different values. The protocol has little control in managing the amount of collateral that can be deposited. This value is henced capped by the lowest values of the collaterals, in our case, ARB. WBTC and WETH deposits effectively has little impact on `reserve.totalDepositAmount`.

```solidity
    function _deposit(
        DataTypes.ReserveInfo storage reserve,
        DataTypes.UserInfo storage user,
        uint256 amount,
        address collateral,
        address to,
        address from
    ) internal {
        require(reserve.isDepositAllowed, JUSDErrors.RESERVE_NOT_ALLOW_DEPOSIT);
        require(amount != 0, JUSDErrors.DEPOSIT_AMOUNT_IS_ZERO);
        IERC20(collateral).safeTransferFrom(from, address(this), amount);
        _addCollateralIfNotExists(user, collateral);
        user.depositBalance[collateral] += amount;
        reserve.totalDepositAmount += amount;
        require(
            user.depositBalance[collateral] <=
                reserve.maxDepositAmountPerAccount,
            JUSDErrors.EXCEED_THE_MAX_DEPOSIT_AMOUNT_PER_ACCOUNT
        );
        require(
            reserve.totalDepositAmount <= reserve.maxTotalDepositAmount,
            JUSDErrors.EXCEED_THE_MAX_DEPOSIT_AMOUNT_TOTAL
        );
        emit Deposit(collateral, from, to, msg.sender, amount);
    }
```

## Impact
Protocol has little control in the collateral limits set since different collateral with vastly different values share the same variable.

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBank.sol#L247-L271

## Tool used

Manual Review

## Recommendation
Consider adding a a way to differentiate `amount` of the different collaterals used. One way is to use oracle to price them.

**Comment by yixxas** [comment]
Escalate for 10 USDC

I believe #5 has failed to illustrate any impact of `reserve.totalDepositAmount` being shared across collaterals hence it was rejected by the sponsor. This issue should be deduped from #5.

The issue here is that using `reserve.totalDepositAmount` as a means of limiting capping maximum deposit amount is not effective. As explained in the report, this is due to the vastly different real value of the tokens used, such as between ARB and WBTC.

As we can see from this require check,

```solidity
        require(
            reserve.totalDepositAmount <= reserve.maxTotalDepositAmount,
            JUSDErrors.EXCEED_THE_MAX_DEPOSIT_AMOUNT_TOTAL
        );
```

`reserve.totalDepositAmount` is checked against `reserve.maxTotalDepositAmount`. It is impossible to set an `amount` for `reserve.maxTotalDepositAmount` that is effective. If the amount set is based on how much we want to limit WBTC, then users can easily DOS deposit by depositing ARB tokens. If amount set is based on `amount` of ARB token, then this limit is ineffective as infinite amount of WBTC can be deposited.

Hence, I believe this issue to be a valid solo medium.

**Comment by JoscelynFarr** [comment]
Hi the reserveInfo is a mapping and the key is collateral's address. So I think we have already differentiated amount of the different collaterals
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBankStorage.sol#L18

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
Not a duplicate of #5
Considering this a non-Issue based on sponsor comments as reserveinfo is a mapping against respective collateral addresses

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yixxas](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/380/#issuecomment-1568345646): accepted
