### ISSUE TITLE
yixxas - `approveTrade()` can be frontrun to steal order sender fee by other valid order sender

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#382]
yixxas

medium

# `approveTrade()` can be frontrun to steal order sender fee by other valid order sender

## Summary
Even though currently, JOJO is the only valid order sender currently, the protocol aims to decentralise matching mechanism in the future, hence adding more order senders in the future.

When that happens, `approveTrade()` becomes a race condition as the caller can frontrun `trade()` and receive the order sender fee instead.

## Vulnerability Detail
`approveTrade()` takes in only 2 parameters, `orderSender` and `tradeData`. All users signature are saved in `tradeData` and transparent on the blockchain. An adversary can frontrun `trade()`, use the same `tradeData`, and hence be the recipient of order sender fee.

## Impact
Order sender fee can be stolen by malicious order sender

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/impl/JOJOExternal.sol#L103C14-L192

## Tool used

Manual Review

## Recommendation
Consider adding `orderSender` as part of the signature used in `tradeData` if we want to limit who is allowed to collect fees, instead of enabling all valid order senders.

**Comment by Trumpero** [comment]
Disagree with the escalation, I believe `approveTrade` function is not permissionless. In the current version, `approveTrade` only permits the perpetual contract to make the call (using the `onlyRegisteredPerp` modifier). And protocol always restricts the sender of this function ([code snippet](https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/impl/JOJOExternal.sol#L112-L115)). It was also mentioned in the contest docs.
<img width="734" alt="Screen Shot 2023-06-14 at 16 31 58" src="https://github.com/sherlock-audit/2023-04-jojo-judging/assets/114548871/cb14f31a-e3a2-4bd8-871d-bc186f195275">
Additionally, front-running is not possible on Arbitrum.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this low based on above comment

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yixxas](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/382/#issuecomment-1568352210): rejected
