### ISSUE TITLE
yixxas - Rich adversary can grief borrowing of all users at no cost

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#387]
yixxas

high

# Rich adversary can grief borrowing of all users at no cost

## Summary
On borrow, protocol has a check that ensures total amount deposited into the protocol, or borrowed does not exceed the GLOBAL max set by the protocol. This check is enforced in `borrow()` and `deposit()`.

A sandwich attack by the adversary can prevent users from borrowing or depositing at practically no cost.

## Vulnerability Detail
The root to this issue is that loans can be borrowed and repayed in the same block. Similarly, collaterals can be deposited and withdrawn in the same block. And if such actions are done in the same block, adversary does not have to pay any interest yet since `block.timestamp` remains the same.The calculated `getTRate()` to determine amount that has to be repaid/withdrawn is the same.

An adversary can sandwich any transaction that is trying to borrow, or deposit by borrowing/deposit a large amount, forcing the protocol to exceed the global limit, and then repaying/withdrawing at the end of the block. This will cause the victim's transcation to revert as it has exceeded the global limit. 

## Impact
1. Borrowing by users can be griefed. This effectively prevents the protocol from working as intended perpetually.
2. A more scheming adversary can force a user's position to be liquidated. They can prevent them from depositing collateral to provide support for their borrows. A user's position who is nearly at risk cannot deposit collateral, and hence be eventually liquidated.

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBank.sol#L274-L305
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBank.sol#L247-L271
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBank.sol#L307-L330
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBank.sol#L332-L363

## Tool used

Manual Review

## Recommendation
Minimally, we can prevent deposit/borrow and withdraw/repay in the same block. We can also consider adding a fee for depositing and borrowing to increase the cost for attacker.

**Comment by yixxas** [comment]
Escalate for 10 USDC

This issue is closed without any explanation. An attacker can basically DOS and prevent deposits of any user by abusing the global deposit limit. 

```solidity
        require(
            reserve.totalDepositAmount <= reserve.maxTotalDepositAmount,
            JUSDErrors.EXCEED_THE_MAX_DEPOSIT_AMOUNT_TOTAL
        );
```

Now, the initial amount needed for this attack depends on the maximum limit set by `reserve.maxTotalDepositAmount`. In my other issue #380, I have explained the reasons why this value is calculated wrongly which increases the likelihood of the attack described in this issue. 

The core issue here is that deposit and withdraw can be done in the same block at this cost, enabling this attack. An attacker can prevent any user from depositing collateral, hence forcing their position to be at risk of being liquidated hence this issue should be a valid high severity.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This issue is closed without any explanation. An attacker can basically DOS and prevent deposits of any user by abusing the global deposit limit. 
> 
> ```solidity
>         require(
>             reserve.totalDepositAmount <= reserve.maxTotalDepositAmount,
>             JUSDErrors.EXCEED_THE_MAX_DEPOSIT_AMOUNT_TOTAL
>         );
> ```
> 
> Now, the initial amount needed for this attack depends on the maximum limit set by `reserve.maxTotalDepositAmount`. In my other issue #380, I have explained the reasons why this value is calculated wrongly which increases the likelihood of the attack described in this issue. 
> 
> The core issue here is that deposit and withdraw can be done in the same block at this cost, enabling this attack. An attacker can prevent any user from depositing collateral, hence forcing their position to be at risk of being liquidated hence this issue should be a valid high severity.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
Front-running or sandwich attack is not possible on Arbitrum. Additionally, users will always be able to repay, ensuring that their positions are not at risk of being forcibly liquidated. Therefore, I believe this issue is invalid.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Based on the comments above on not being able to sandwich on arbitrum currently considering this issue low.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yixxas](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/387/#issuecomment-1568417804): rejected
