### ISSUE TITLE
yixxas - `primaryCredit` and `secondaryCredit` are assumed to be 18 decimals in the calculations used but it is not the case

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#388]
yixxas

high

# `primaryCredit` and `secondaryCredit` are assumed to be 18 decimals in the calculations used but it is not the case

## Summary
The calculations used by the protocol, such as in `isSafe()` and `requestLiquidation` assumes that `state.primaryCredit` and `state.secondaryCredit` is 18 decimals, but they are in fact the decimals of the underlying assets used. In our case, they are USDC and JUSD respectively, hence both values are 6 decimals

## Vulnerability Detail

We first note that when we deposit, the line `state.primaryCredit[to] += SafeCast.toInt256(primaryAmount)` tells us that the value saved to `state.primaryCredit` is `primaryAmount`, which uses the same decimals as the underlying asset, hence we can be certain that decimals of `primaryCredit` is 6 decimals. This is also true for `secondaryCredit`.

```solidity
    function deposit(
        Types.State storage state,
        uint256 primaryAmount,
        uint256 secondaryAmount,
        address to
    ) external {
        if (primaryAmount > 0) {
            IERC20(state.primaryAsset).safeTransferFrom(
                msg.sender,
                address(this),
                primaryAmount
            );
            state.primaryCredit[to] += SafeCast.toInt256(primaryAmount);
        }
        if (secondaryAmount > 0) {
            IERC20(state.secondaryAsset).safeTransferFrom(
                msg.sender,
                address(this),
                secondaryAmount
            );
            state.secondaryCredit[to] += secondaryAmount;
        }
        emit Deposit(to, msg.sender, primaryAmount, secondaryAmount);
    }
```

Next, in `getTotalExposure`, we see these calculations. Decimal math is used hence we know `netPositionValue` is 18 decimals. 

```solidity
netPositionValue += paperAmount.decimalMul(price) + creditAmount;
uint256 exposureIncrement = paperAmount.decimalMul(price).abs();
exposure += exposureIncrement;
maintenanceMargin +=
	(exposureIncrement * params.liquidationThreshold) /
	Types.ONE;
```

This value is then passed into `_isSafe()` and added with `primaryCredit`, but they are of different decimals as we have previously established.

```solidity
function _isSafe(Types.State storage state, address trader)
	internal
	view
	returns (bool)
{
	(
		int256 netPositionValue,
		,
		uint256 maintenanceMargin
	) = getTotalExposure(state, trader);

	// net value >= maintenanceMargin
	return
		netPositionValue +
			state.primaryCredit[trader] +
			SafeCast.toInt256(state.secondaryCredit[trader]) >=
		SafeCast.toInt256(maintenanceMargin);
}
```

The same is true for `requestLiquidation()`.

## Impact
Values of different decimals added to each other means wrong accounting of the protocol for important values.

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/lib/Funding.sol#L57-L79
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/lib/Liquidation.sol#L87-L104

## Tool used

Manual Review

## Recommendation
Consider converting `primaryCredit` and `secondaryCredit` to 18 decimals when we first deposit them.

**Comment by yixxas** [comment]
Escalate for 10 USDC

I did a relook on this issue and believes that it is valid. The sponsor might have misunderstood the issue since it does not matter that price correction is made in oracle, since calculations in the contract itself is wrong.

We first see the implementation of balanceOf. It returns `paper` and `credit` amount. Decimals of both of these are expected to be 18 decimals as seen in the docs [here](https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/impl/Perpetual.sol#L29-L34)

[https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/impl/Perpetual.sol#LL73C1-L81C1](https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/impl/Perpetual.sol#LL73C1-L81C1)
```solidity
    function balanceOf(
        address trader
    ) external view returns (int256 paper, int256 credit) {
        paper = int256(balanceMap[trader].paper);
        credit =
            paper.decimalMul(fundingRate) +
            int256(balanceMap[trader].reducedCredit);
    }
```

`balanceOf` is used in `getTotalExposure()`. Since both `creditAmount` and `paperAmount` are 18 decimals, we know that `netPositionValue` MUST be 18 decimals.

[https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/lib/Liquidation.sol#L53-L85](https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/lib/Liquidation.sol#L53-L85)
```solidity
    function getTotalExposure(Types.State storage state, address trader)
        public
        view
        returns (
            int256 netPositionValue,
            uint256 exposure,
            uint256 maintenanceMargin
        )
    {
        // sum net value and exposure among all markets
        for (uint256 i = 0; i < state.openPositions[trader].length; ) {
            (int256 paperAmount, int256 creditAmount) = IPerpetual(
                state.openPositions[trader][i]
            ).balanceOf(trader);
            Types.RiskParams storage params = state.perpRiskParams[
                state.openPositions[trader][i]
            ];
            int256 price = SafeCast.toInt256(
                IMarkPriceSource(params.markPriceSource).getMarkPrice()
            );

            netPositionValue += paperAmount.decimalMul(price) + creditAmount;
            uint256 exposureIncrement = paperAmount.decimalMul(price).abs();
            exposure += exposureIncrement;
            maintenanceMargin +=
                (exposureIncrement * params.liquidationThreshold) /
                Types.ONE;

            unchecked {
                ++i;
            }
        }
    }
```

`netPositionValue` is added to `state.primaryCredit` in `_isSafe` hence `state.primaryCredit` MUST be 18 decimals too. But this is incorrect based on our initial assumption, as `state.primaryCredit` decimal is decimal of the underlying token, which is 6 decimals, because of this line. 

```solidity
            IERC20(state.primaryAsset).safeTransferFrom(
                msg.sender,
                address(this),
                primaryAmount
            );
            state.primaryCredit[to] += SafeCast.toInt256(primaryAmount);
``` 

We can see that various issues scaling/decimal issues in past contests such as  https://github.com/sherlock-audit/2023-01-derby-judging/issues/202 and https://github.com/sherlock-audit/2023-01-derby-judging/issues/132 are both high severity issues. A position can be considered safe, when it is not hence allowing users to borrow more than they should.

With these reasons, I believe this issue to be a valid solo high.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> I did a relook on this issue and believes that it is valid. The sponsor might have misunderstood the issue since it does not matter that price correction is made in oracle, since calculations in the contract itself is wrong.
> 
> We first see the implementation of balanceOf. It returns `paper` and `credit` amount. Decimals of both of these are expected to be 18 decimals as seen in the docs [here](https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/impl/Perpetual.sol#L29-L34)
> 
> [https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/impl/Perpetual.sol#LL73C1-L81C1](https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/impl/Perpetual.sol#LL73C1-L81C1)
> ```solidity
>     function balanceOf(
>         address trader
>     ) external view returns (int256 paper, int256 credit) {
>         paper = int256(balanceMap[trader].paper);
>         credit =
>             paper.decimalMul(fundingRate) +
>             int256(balanceMap[trader].reducedCredit);
>     }
> ```
> 
> `balanceOf` is used in `getTotalExposure()`. Since both `creditAmount` and `paperAmount` are 18 decimals, we know that `netPositionValue` MUST be 18 decimals.
> 
> [https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/lib/Liquidation.sol#L53-L85](https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/lib/Liquidation.sol#L53-L85)
> ```solidity
>     function getTotalExposure(Types.State storage state, address trader)
>         public
>         view
>         returns (
>             int256 netPositionValue,
>             uint256 exposure,
>             uint256 maintenanceMargin
>         )
>     {
>         // sum net value and exposure among all markets
>         for (uint256 i = 0; i < state.openPositions[trader].length; ) {
>             (int256 paperAmount, int256 creditAmount) = IPerpetual(
>                 state.openPositions[trader][i]
>             ).balanceOf(trader);
>             Types.RiskParams storage params = state.perpRiskParams[
>                 state.openPositions[trader][i]
>             ];
>             int256 price = SafeCast.toInt256(
>                 IMarkPriceSource(params.markPriceSource).getMarkPrice()
>             );
> 
>             netPositionValue += paperAmount.decimalMul(price) + creditAmount;
>             uint256 exposureIncrement = paperAmount.decimalMul(price).abs();
>             exposure += exposureIncrement;
>             maintenanceMargin +=
>                 (exposureIncrement * params.liquidationThreshold) /
>                 Types.ONE;
> 
>             unchecked {
>                 ++i;
>             }
>         }
>     }
> ```
> 
> `netPositionValue` is added to `state.primaryCredit` in `_isSafe` hence `state.primaryCredit` MUST be 18 decimals too. But this is incorrect based on our initial assumption, as `state.primaryCredit` decimal is decimal of the underlying token, which is 6 decimals, because of this line. 
> 
> ```solidity
>             IERC20(state.primaryAsset).safeTransferFrom(
>                 msg.sender,
>                 address(this),
>                 primaryAmount
>             );
>             state.primaryCredit[to] += SafeCast.toInt256(primaryAmount);
> ``` 
> 
> We can see that various issues scaling/decimal issues in past contests such as  https://github.com/sherlock-audit/2023-01-derby-judging/issues/202 and https://github.com/sherlock-audit/2023-01-derby-judging/issues/132 are both high severity issues. A position can be considered safe, when it is not hence allowing users to borrow more than they should.
> 
> With these reasons, I believe this issue to be a valid solo high.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
Hi In the real transaction, 
1. the paper amount is based on decimal 18
2. the credit amount is based on decimal 6(case it is the USDC)
3. netValue is based on decimal 6
4. Primary credit and secondary credit is also based on decimal 6
we will update the docs
You can see the testnet tx: https://testnet.arbiscan.io/tx/0xeb9f056f88df43602cea3aeb73cfb463b0650dde1f9c1f77e0383644a6e0bd89#eventlog

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue a low and the docs mention 1e18 for paper but nothing for credit, the code seems to work as expected based on Sponsor comments. This is a documentation update.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [yixxas](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/388/#issuecomment-1568399899): rejected
