### ISSUE TITLE
GalloDaSballo - Safety of `updateReserveParam` is not checked, which can bring the protocol to a risky state

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#408]
GalloDaSballo

medium

# Safety of `updateReserveParam` is not checked, which can bring the protocol to a risky state

## Summary

`_liquidationMortgageRate` should be checked against `_initialMortgageRate` before allowing it to be changed

## Vulnerability Detail

Initial Mortgage rate may be close or higher than `_liquidationMortgageRate`, because no check is applied, this can cause the system to trigger liquidations or be in an incorrect state.

Which can break the safety parameters

InitialMortgageRate may be set improperly, which would cause:
- Borrowing too much
- Instant Liquidations

Since the value is not checked against `liquidationMortgageRate`

Additionally, the value is not checked against `liquidationPriceOff` which may cause bad debt

## Impact

All depositors may be incorrectly liquidated

## Code Snippet

https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDOperation.sol#L203-L210

## Tool used

Manual Review

## Recommendation

Check that `_initialMortgageRate` > `_liquidationMortgageRate`

**Comment by thangtranth** [comment]
Escalate for 10 USDC

This issue belongs to the Admin Input category. The issue can only happen if the admin inputs an incorrect value and admin role is considered trusted in this contest. 

It is a valid low/info issue.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This issue belongs to the Admin Input category. The issue can only happen if the admin inputs an incorrect value and admin role is considered trusted in this contest. 
> 
> It is a valid low/info issue.
> 

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
This is a trusted admin input validation issue. This is a valid low

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [thangtranth](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/{self.issue_number}/#issuecomment-{self.comment_id}): accepted

**Comment by IAm0x52** [comment]
Fix looks good. UpdateReserveParam now validates _initialMortgageRate
