### ISSUE TITLE
Delvir0 - Insufficient signature data check could lead to signature replay

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#414]
Delvir0

high

# Insufficient signature data check could lead to signature replay

## Summary
Due to missing nonce check, a signature of a trade could be replayed by an attacker (grieving)
## Vulnerability Detail
Signature is checked by two aspects:
1. `require(recoverSigner == order.signer)`
2. `require(Trading._info2Expiration(order.info) >= block.timestamp`

Since there's no nonce, the signature is not unique and therefore can be replayed within the `_info2Expiration` time.
## Impact
Order can be placed multiple times due to a signature replay attack
## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/impl/JOJOExternal.sol#L139-L146
## Tool used

Manual Review

## Recommendation
Implement a nonce check

**Comment by syjcnss** [comment]
Escalate for 10 USDC.
Nonce is indeed included onchain but the problem here is that it's not checked onchain.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC.
> Nonce is indeed included onchain but the problem here is that it's not checked onchain.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
I think the protocol only needs to ensure that the nonce is different so that the transaction hash is different to determine that this is the only transaction. What is the specific attack scenario you mentioned?

**Comment by Trumpero** [comment]
I disagree with the escalation. The signature of an order can be used multiple times until it fully matches the specified amount ([code snippet](https://github.com/sherlock-audit/2023-04-jojo/blob/main/smart-contract-EVM/contracts/impl/JOJOExternal.sol#L158-L163)), so I believe this is a non-issue. Furthermore, the use of a nonce ensures that each order has a unique hash, even in cases where other fields of the orders are the same.

**Comment by hrishibhat** [comment]
Result:
Low
Has duplicates
In addition to the mention of the known issue in the readme, Based on the above comments considering this issue as low

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [syjcnss](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/414/#issuecomment-1568730580): rejected
