### ISSUE TITLE
ArbitraryExecution - Users that have open positions in perpetuals that have been unregistered can never have their bad debt handled

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#441]
ArbitraryExecution

medium

# Users that have open positions in perpetuals that have been unregistered can never have their bad debt handled

## Summary

Users that have open positions in perpetuals that have been unregistered can never have their bad debt handled.

## Vulnerability Detail

The [`handleBadDebt` function](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Liquidation.sol#L399) can be called from either a [`Perpetual` contract](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/impl/Perpetual.sol#L165) during liquidation or directly from the [`JOJOExternal` contract](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/impl/JOJOExternal.sol#L56), as it does not have the `onlyRegisteredPerp` modifier. This intrinsically makes sense, as the protocol may need to directly handle bad debt from users in a perpetual agnostic way. However, `handleBadDebt` will only transfer bad debt to the insurance account if [both conditions](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Liquidation.sol#L402-L405) are met. Notice the length of `openPositions` for the trader address has to be zero.

Each open position corresponds to a perpetual address at which a trader has an open position for. These open positions can only be closed, and subsequently removed from `openPositions`, by calling [`_realizePnl`](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/impl/JOJOExternal.sol#L95-L100). `_realizePnl` is only callable by a registered perpetual, and can only remove the address of the perpetual contract that initiated the top-level call. Therefore, if a perpetual is unregistered, any user that had an open position in that perpetual will be unable to remove the perpetual address from their `openPositions` array. This is because the calls that facilitate the `_realizePnl` function call must pass the [`onlyRegisteredPerp`](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/impl/JOJOStorage.sol#L35) modifier, but if a perpetual has been unregistered the modifier will revert. Therefore, for any subsequent liquidations on these users from any other perpetual address, the protocol will be unable to assume any lingering bad debt.

## Impact

An accumulation of lingering bad debt that cannot be assumed by the insurance account could cause the JOJO protocol to destabilize.

## Code Snippet

https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Liquidation.sol#L402-L405

```solidity
function handleBadDebt(Types.State storage state, address liquidatedTrader)
    external
{
    if (
        state.openPositions[liquidatedTrader].length == 0 &&
        !Liquidation._isSafe(state, liquidatedTrader)
    ) {
        int256 primaryCredit = state.primaryCredit[liquidatedTrader];
        uint256 secondaryCredit = state.secondaryCredit[liquidatedTrader];
        state.primaryCredit[state.insurance] += primaryCredit;
        state.secondaryCredit[state.insurance] += secondaryCredit;
        state.primaryCredit[liquidatedTrader] = 0;
        state.secondaryCredit[liquidatedTrader] = 0;
        emit HandleBadDebt(
            liquidatedTrader,
            primaryCredit,
            secondaryCredit
        );
    }
}
```

## Tool used

Manual review.

## Recommendation

The [expression](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Liquidation.sol#L402-L405) in `handleBadDebt` should be modified to check for open positions on perpetuals that have been unregistered. If an unregistered position is found, the PNL for that position should be realized; this means the internal `_realizePnl` function will also need to be modified to allow the `JOJODealer` contract to specify a perpetual address. Then, once any open positions in unregistered perpetuals have been closed, the original expression in `handleBadDebt` can be evaluated.

**Comment by arbitrary-sparrow** [comment]
Escalate for 10 USDC

Similar to the escalation for https://github.com/sherlock-audit/2023-04-jojo-judging/issues/447, the sponsor's dispute to the issue is the first-ever mention that they will check to make sure there are no active positions in a perpetual before it is unregistered. Neither the [documentation](https://jojo-docs.netlify.app/list-and-delist) nor [JOJO's responses](https://discord.com/channels/812037309376495636/1100073679762755625/1102780385911373915) about the conditions for which a perpetual will be unregistered have ever stated that they will ensure there are no active positions.

Again, this claim is impossible to uphold because users will be able to create new positions up until JOJO submits a transaction to unregister a perpetual. JOJO cannot guarantee that a perpetual that is about to be unregistered has no open positions, and therefore an attacker would be able to manipulate `_isAllSafe` like the issue suggests.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Similar to the escalation for https://github.com/sherlock-audit/2023-04-jojo-judging/issues/447, the sponsor's dispute to the issue is the first-ever mention that they will check to make sure there are no active positions in a perpetual before it is unregistered. Neither the [documentation](https://jojo-docs.netlify.app/list-and-delist) nor [JOJO's responses](https://discord.com/channels/812037309376495636/1100073679762755625/1102780385911373915) about the conditions for which a perpetual will be unregistered have ever stated that they will ensure there are no active positions.
> 
> Again, this claim is impossible to uphold because users will be able to create new positions up until JOJO submits a transaction to unregister a perpetual. JOJO cannot guarantee that a perpetual that is about to be unregistered has no open positions, and therefore an attacker would be able to manipulate `_isAllSafe` like the issue suggests.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue low based on sponsor comment.
> Our current matching engine is centralized, so we can confirm that we will not remove perpetual until everyone closes their positions.

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ArbitraryExecution](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/441/#issuecomment-1570545201): rejected
