### ISSUE TITLE
ArbitraryExecution - `_isAllSafe` can derive a `markPrice` of zero for any perpetual if a trader has more open positions than active perpetuals

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#447]
ArbitraryExecution

high

# `_isAllSafe` can derive a `markPrice` of zero for any perpetual if a trader has more open positions than active perpetuals

## Summary

The `markPrice` caching logic in `_isAllSafe` can return a price of zero for any perpetual if a trader has more open positions than active perpetuals.

## Vulnerability Detail

The internal function [`_isAllSafe`](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Liquidation.sol#L129) attempts to cache the mark prices of all active perpetuals as a gas saving maneuver. However, as part of caching the values, the code makes an [implicit assumption](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Liquidation.sol#L134-L136) that the total number of perpetuals to cache price for is equivalent to the number of active perpetuals. The number of active perpetuals is then assumed to be the max number of open positions for any given trader, which is incorrect. When a perpetual is [unregistered](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Operation.sol#L50-L57), it is simply removed from the `state.registeredPerp` array. This does not remove the perpetual address from a trader's `openPositions` array, which corresponds to the perpetual addresses that a trader has an open position in. This causes incorrect behavior in `_isAllSafe` when calculating the price of a perpetual, as a price will only be calculated if the perpetual is found before the [nested `for` loop](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Liquidation.sol#L151) completes, otherwise the value will remain as the `uint256` default value of zero.

An attacker can use this incorrect behavior in the following scenario:

1. JOJO announces a perpetual is being de-listed, in order to de-list a perpetual, the perpetual itself needs to be unregistered in order to swap the Chainlink oracle for a fixed price oracle. Additionally, unregistering a perpetual allows the backend to sync; this makes the on-chain change non-atomic which opens a window for the attacker. Before the perpetual is temporarily unregistered, an attacker opens a position in that perpetual.
2. The attacker then re-arranges their [`openPositions`](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Types.sol#L31) array by opening and closing positions in other perpetuals, such that the following prerequisites are met:

* The attacker has an open position in all active and soon-to-be unregistered perpetuals, such that their `openPositions` array will be greater than the number of active, registered perpetuals (once the specific perpetual is temporarily unregistered).
* The attacker has placed the perpetual they want to attack at the end of their `openPositions` array.

3. The attacker now sets up a trade as a taker, intending to create a large short position on the perpetual that is the last element in their `openPositions` array. The attacker is matched with one or more makers. Once the trade is matched, [`_isAllSafe`](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/impl/Perpetual.sol#L109) is called to ensure the traders involved still have healthy positions after the trade.
4. Because the attacker is the taker, their `openPositions` perpetual addresses will be iterated over and used to cache the `markPrice`s for the rest of the trader perpetuals. All of the attacker's open positions are [iterated over](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Liquidation.sol#L145-L146), and the mark price is attempted to be found for the given perpetual. However, the [nested `for` loop](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Liquidation.sol#L150-L151) will only iterate over the length of active perpetuals, which is now one less than the total number of perpetuals the attacker has a position in. This means the perpetual at the end of the array will not have its mark price set, meaning the default value of zero will be used as the price. This means when [calculating `maintenanceMargin` and `netValue`](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Liquidation.sol#L170-L176), `maintenanceMargin` will not be incremented, and `netValue` will only have the `credit` added to it. Since the attacker opened a short position, they following [check](https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Liquidation.sol#L182-L183) will always succeed. For the makers, their `netValue` will not include the positive `paperAmount` due to the `markPrice` of the perpetual being 0, so only their previous credit will be accounted for in the health check. Assuming they have healthy positions such that `netValue >= newCredit`, the health check will also still pass for them.

## Impact

Assuming an attacker is able to match their taker order with a maker whose position is healthy enough to absorb the loss in credit without being given the new `paperAmount` they should have received for matching, the attacker can create short positions that would otherwise be considered unhealthy. Typically, trades that result in unhealthy accounts would revert, but due to the price caching logic bug, it will not. Creating intentionally unhealthy positions means that the JOJO protocol will be forced to assume the bad debt that has been created, which in turn could destabilize the protocol.

## Code Snippet

https://github.com/JOJOexchange/smart-contract-EVM/blob/4a95a8e9a6367ae88dc827e29467229cb5bbad4f/contracts/lib/Liquidation.sol#L133-L165

```solidity
{
...
    // cache mark price
    uint256 totalPerpNum = state.registeredPerp.length;
    address[] memory perpList = new address[](totalPerpNum);
    int256[] memory markPriceCache = new int256[](totalPerpNum);
    // check each trader's maintenance margin and net value
    for (uint256 i = 0; i < traderList.length; ) {
        address trader = traderList[i];
        uint256 maintenanceMargin;
        int256 netValue = state.primaryCredit[trader] +
            SafeCast.toInt256(state.secondaryCredit[trader]);
        // go through all open positions
        for (uint256 j = 0; j < state.openPositions[trader].length; ) {
            address perp = state.openPositions[trader][j];
            Types.RiskParams storage params = state.perpRiskParams[perp];
            int256 markPrice;
            // use cached price OR cache it
            for (uint256 k = 0; k < totalPerpNum; ) {
                if (perpList[k] == perp) {
                    markPrice = markPriceCache[k];
                    break;
                }
                // if not, query mark price and cache it
                if (perpList[k] == address(0)) {
                    markPrice = SafeCast.toInt256(
                        IMarkPriceSource(params.markPriceSource)
                            .getMarkPrice()
                    );
                    perpList[k] = perp;
                    markPriceCache[k] = markPrice;
                    break;
                }
                ...
            }
            ...
        }
        ...
    }
    ...
}
```

## Tool used

Manual review.

## Recommendation

When caching the prices of perpetuals, JOJO should not assume that `state.registeredPerp.length` is the max size of the `markPriceCache` array. If a trader is encountered whose perpetual in their `openPositions` array did not successfully retrieve a `markPrice` from the `markPriceCache`, then JOJO will need to retrieve the `markPrice`, and resize `markPriceCache` so that the perpetual's price can be added to the cache. Alternatively, JOJO could create a new state variable that holds the total number of created perpetuals (both registered and unregistered), and use that as the length of the `markPriceCache` and as the length for the nested `for` loop.

**Comment by arbitrary-cr0** [comment]
Escalate for 10 USDC

The sponsor dispute to the issue is the first-ever mention that they will check to make sure there are no active positions in a perpetual before it is unregistered. Neither the [documentation](https://jojo-docs.netlify.app/list-and-delist) nor [JOJO's responses](https://discord.com/channels/812037309376495636/1100073679762755625/1102780385911373915) about the conditions for which a perpetual will be unregistered have ever stated that they will ensure there are no active positions. 

Additionally, this claim is impossible to uphold because users will be able to create new positions up until JOJO submits a transaction to unregister a perpetual. JOJO cannot guarantee that a perpetual that is about to be unregistered has no open positions, and therefore an attacker would be able to manipulate `_isAllSafe` like the issue suggests.

**Comment by arbitrary-sparrow** [comment]
Escalate for 10 USDC

Reposting @arbitrary-cr0 so it gets picked up by the bot:

The sponsor dispute to the issue is the first-ever mention that they will check to make sure there are no active positions in a perpetual before it is unregistered. Neither the [documentation](https://jojo-docs.netlify.app/list-and-delist) nor [JOJO's responses](https://discord.com/channels/812037309376495636/1100073679762755625/1102780385911373915) about the conditions for which a perpetual will be unregistered have ever stated that they will ensure there are no active positions. 

Additionally, this claim is impossible to uphold because users will be able to create new positions up until JOJO submits a transaction to unregister a perpetual. JOJO cannot guarantee that a perpetual that is about to be unregistered has no open positions, and therefore an attacker would be able to manipulate `_isAllSafe` like the issue suggests.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Reposting @arbitrary-cr0 so it gets picked up by the bot:
> 
> The sponsor dispute to the issue is the first-ever mention that they will check to make sure there are no active positions in a perpetual before it is unregistered. Neither the [documentation](https://jojo-docs.netlify.app/list-and-delist) nor [JOJO's responses](https://discord.com/channels/812037309376495636/1100073679762755625/1102780385911373915) about the conditions for which a perpetual will be unregistered have ever stated that they will ensure there are no active positions. 
> 
> Additionally, this claim is impossible to uphold because users will be able to create new positions up until JOJO submits a transaction to unregister a perpetual. JOJO cannot guarantee that a perpetual that is about to be unregistered has no open positions, and therefore an attacker would be able to manipulate `_isAllSafe` like the issue suggests.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
Our current matching engine is centralized, so we can confirm that we will not remove perpetual until everyone closes their positions.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Considering this issue low based on Sponsor comment

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [ArbitraryExecution](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/447/#issuecomment-1570575047): rejected
