### ISSUE TITLE
BenRai - If user has to many open positions, the function `getTotalExposure()` will fail because it runs out of gas

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#47]
BenRai

high

# If user has to many open positions, the function `getTotalExposure()` will fail because it runs out of gas

## Summary

If a user has to many open positions the function `getTotalExposure()` will run out of gas while calculating the `netPositionValue` and looping over ` openPositions[trader]`. This will result in the failure of all functions that call the function `getTotalExposure()`.

## Vulnerability Detail

The functions ` _isSafe ` and `_isSolidSafe` are calling `getTotalExposure()` and can therefore run out of gas. 

 The following “end functions” are affected by this and will also run out of gas:

`Perpetual.trade()`,
`Perpetual. liquidate()` (trough `Liquidation.handleBadDebt()`),
‘Funding. executeWithdraw()’ (through `Funding. _withdraw`),
`Liquidation.requestLiquidation()` (trough `Liquidation.getLiquidateCreditAmount()`)
`JOJOExternal. approveTrade()`

## Impact

A user that has to many open positions can not withdraw any assets even if he would meet the necessary criteria.  (‘Funding. executeWithdraw()’ is failing)  He would be forced to close positions to free his assets again by using the function `_realizePnl`. Since this function `_realizePnl` also runs a loop over all open Positions of the user  to find the position that should be closed, the user would need to close one of his oldest positions to avoid running out of gas here also. If the user has eg. 100 positions open and he would need e.g. 90 to be able withdraw his assets he would be forced to close 10 positions. If the positions that he can close without running out of gas using the function `_realizePnl`  are all out of profit, he might be forced to realize loses. This might lead to him leaving the JOJO ecosystem. This is especially bad for the exchange since individuals who have a lot of open positions are the once that trade a lot and bring in the most fee revenues.

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/lib/Liquidation.sol#L63-L84

## Tool used

Manual Review

## Recommendation

Set a cap of open positions one address can have. If the user wands to open more positions he can create a sub account and open new positions there.

**Comment by imp0wd3r** [comment]
Escalate for 10 USDC
Same reason with https://github.com/sherlock-audit/2023-04-jojo-judging/issues/348

The development team has clearly stated that the DoS caused by too many perpetuals is a known issue.

> Q: Please list any known issues/acceptable risks that should not result in a valid finding.
> 12.DOS attack possible for trading:
> b. _realizePnl function loops over an unbounded array within the openPositions
mapping, but there is a limit on the number of registered perpetuals to avoid
reaching the block gas limit.

Additionally, these two vulnerabilities are duplicates.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> Same reason with https://github.com/sherlock-audit/2023-04-jojo-judging/issues/348
> 
> The development team has clearly stated that the DoS caused by too many perpetuals is a known issue.
> 
> > Q: Please list any known issues/acceptable risks that should not result in a valid finding.
> > 12.DOS attack possible for trading:
> > b. _realizePnl function loops over an unbounded array within the openPositions
> mapping, but there is a limit on the number of registered perpetuals to avoid
> reaching the block gas limit.
> 
> Additionally, these two vulnerabilities are duplicates.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by arbitrary-cr0** [comment]
Escalate for 10 USDC

This is a duplicate of https://github.com/sherlock-audit/2023-04-jojo-judging/issues/348. Both issues misunderstand what is stored in the `openPositions` array for a trader.

**Comment by arbitrary-sparrow** [comment]
Escalate for 10 USDC

Reposting @arbitrary-cr0 so it gets picked up by the bot:

This is a duplicate of https://github.com/sherlock-audit/2023-04-jojo-judging/issues/348. Both issues misunderstand what is stored in the openPositions array for a trader.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> Reposting @arbitrary-cr0 so it gets picked up by the bot:
> 
> This is a duplicate of https://github.com/sherlock-audit/2023-04-jojo-judging/issues/348. Both issues misunderstand what is stored in the openPositions array for a trader.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by m9800** [comment]
Escalate for 10 USDC
The number of Open positions of a user can never be greater than the total positions available in the system. Additionally, when profit and loss is realized (_realizePnl), positions with 0 credit are popped from the array. 
https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/lib/Position.sol#L34

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> The number of Open positions of a user can never be greater than the total positions available in the system. Additionally, when profit and loss is realized (_realizePnl), positions with 0 credit are popped from the array. 
> https://github.com/sherlock-audit/2023-04-jojo/blob/6090fef68932b5577abf6b5aa26eb1e579353c57/smart-contract-EVM/contracts/lib/Position.sol#L34

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by Trumpero** [comment]
Agree with the escalations, this issue is a duplicate of #348 and should be invalid.

**Comment by hrishibhat** [comment]
Result:
Low 
Has duplicates
Given that unbounded array over openPositions is a known issue and the fact that the value stored in the openPositions array for a trader is the address of the perpetual, considering this issue as low

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [imp0wd3r](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/47/#issuecomment-1568466568): accepted
- [ArbitraryExecution](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/47/#issuecomment-1570572231): accepted
- [m9800](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/47/#issuecomment-1571022895): accepted
