### ISSUE TITLE
Ruhum - JUSDBank should mint/burn JUSD instead of only transferring it

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-04-jojo-judging#74]
Ruhum

medium

# JUSDBank should mint/burn JUSD instead of only transferring it

## Summary
The JUSDBank should be minting & burning JUSD instead of transferring it around when a user borrows or repays JUSD.

## Vulnerability Detail
Borrowing JUSD from JUSDBank is supposed to be the only way to get any fresh JUSD. But, the bank contract never mints any new tokens. Instead, it expects to have a certain amount of JUSD tokens assigned to it that it can lend to users.
Meaning, the actual owner of JUSD is not the bank contract but some other address. Most likely an EOA/Multsig the protocol team controls. That address has to fund the bank for it to be able to operate properly.

## Impact
Multiple issues arise from that design:
**1. `JUSD.totalSupply()` doesn't represent the actual amount of JUSD that's in circulation.**
Any JUSD assigned to JUSDBank isn't in circulation. For those tokens to enter the market, they have to be borrowed by someone first. That breaks the ERC20 standard because `totalSupply` doesn't really represent the number of tokens that were borrowed. Additionally, this will artificially inflate the token's market cap. By funding JUSDBank with billions of JUSD the market cap will be billions of dollars as well ($1 * totalSupply) which is not really the case since no one borrowed those tokens. 
**2. JUSDBank might run out of funds in volalite market conditions**
The crypto market is inherently unpredictable. There's the possibility of the JUSDBank contract running out of JUSD to lend out causing the lending market to halt until the protocol team adds additional funds. While that is only a temporary issue, it breaks the design philosophy of the token: put down X amount of collateral to borrow Y amount of JUSD at any time.

## Code Snippet
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBank.sol#L292
https://github.com/sherlock-audit/2023-04-jojo/blob/main/JUSDV1/src/Impl/JUSDBank.sol#L325
## Tool used

Manual Review

## Recommendation
JUSDBank should be the owner of the JUSD token. When a user borrows JUSD it should mint fresh tokens. When the user repays their debt, it should burn those tokens. 

Duplicate of #306

**Comment by 0xruhum** [comment]
Escalate for 10 USDC

This is a duplicate of #306. I describe the same issue of `totalSupply` not matching the actual amount of JUSD that's in circulation which is determined by the amount of USD in the system. Thus, JUSD is not backed 1:1 with USD. Additionally, I describe the issue of users not being able to borrow any funds in case the JUSD supply in JUSDBank runs out.

**Comment by sherlock-admin** [comment]
> Escalate for 10 USDC
> 
> This is a duplicate of #306. I describe the same issue of `totalSupply` not matching the actual amount of JUSD that's in circulation which is determined by the amount of USD in the system. Thus, JUSD is not backed 1:1 with USD. Additionally, I describe the issue of users not being able to borrow any funds in case the JUSD supply in JUSDBank runs out.

You've created a valid escalation for 10 USDC!

To remove the escalation from consideration: Delete your comment.

You may delete or edit your escalation comment anytime before the 48-hour escalation window closes. After that, the escalation becomes final.

**Comment by JoscelynFarr** [comment]
The reason for this design is that the risk control is more reliable. Considering that the security of the entire system is determined by multiple signatures, we decided not to modify.

**Comment by hrishibhat** [comment]
Result:
Medium
Duplicate of #306

**Comment by sherlock-admin** [comment]
Escalations have been resolved successfully!

Escalation status:
- [0xruhum](https://github.com/sherlock-audit/2023-04-jojo-judging/issues/74/#issuecomment-1571576455): accepted
